### ISSUE TITLE
New to docker - what am I doing wrong?

### ISSUE THREAD

**Issue by XDGFX** [docker/hub-feedback#1147]
I'm trying to set up my media server using docker.

I'm using the containers from linuxserver.io, and I'm running docker for windows on windows 10.

The installation instructions say "copy all the lines below and paste into a docker prompt"

`docker create \
--name=plex \
--net=host \
--restart=always \
-e VERSION=latest \
-e PUID=1001 -e PGID=1001 \
-e TZ=Europe/London \
-v /home/docker/plex/config:/config \
-v /home/docker/plex/tvshows:/data/tvshows \
-v /home/docker/plex/movies:/data/movies \
-v /home/docker/plex/transcode:/transcode \
linuxserver/plex`

but when I paste the following into command prompt it tries to run each line individually

`docker create /
--name=plex /
--net=host /
--restart=always /
-e VERSION=latest /
-e PUID=1001 /
-e PGID=1001 /
-e TZ=Europe/London /
-v D:\Docker Containers\Plex\config:/config /
-v F:\TV:/data/tvshows /
-v E:\Films:/data/movies /
-v D:\Music\Callum's Library\Music:/data/music /
-v D:\Plex Music:/data/plexmusic /
-v D:\Docker Containers\Plex\transcode:/transcode /
linuxserver/plex`

I'm completely new so I have no idea where to start working out what's wrong. Any help is appreciated!

edit: each command is on a new line, github just joins them all together

**Comment by TBK0000** [comment]
This is not the right place for Docker support. This repo is for issues related to hub.docker.com

Some tips:
- The command is intended for Linux.
- The trailing  \  means that the command input is continuing on a new line.
- The volume paths are wrong they are absolute paths for a Linux system.
- On Windows it is currently not possible to use the "host" network since Docker runs a Hyper-V virtual machine with a special Linux distro and the VM gets network access through NAT.

Plex guide for Windows 10:
I recommend using the official Plex image -https://github.com/plexinc/pms-docker

Create a folder somewhere on your system.
Inside the folder hold Shift down and right click, select "Open PowerShell window here" paste in the following command as one line and hit Enter:

Remember to edit the <blabla> parts first. You can get the claim token here https://www.plex.tv/claim

`docker run -d --name plex -p 32400:32400/tcp -p 3005:3005/tcp -p 8324:8324/tcp -p 32469:32469/tcp -p 1900:1900/udp -p 32410:32410/udp -p 32412:32412/udp -p 32413:32413/udp -p 32414:32414/udp -e TZ="<timezone>" -e PLEX_CLAIM="" -e ADVERTISE_IP="http://<hostIPAddress>:32400/" -h <HOSTNAME> -v $pwd/config:/config -v $pwd/transcode:/transcode -v $pwd/media:/data plexinc/pms-docker`


To access the control panel visit https://127.0.0.1:32400
