### ISSUE TITLE
Is it possible to enable yearly payment?

### ISSUE THREAD

**Issue by makimat** [docker/hub-feedback#1231]
I'd like to keep the monthly hassle with invoices and accounting in the minimum, thus would appreciate if it was possible to pay the docker hub subscription yearly in advance. Is this possible?

**Comment by vineethvijay-MyT** [comment]
+1 for this,

**Comment by jinsem** [comment]
Hey. My company has to support multiply organization of docker hub and we have to pay multiply bills every single month. It will be much more useful if docker hub allowed annual payments.

**Comment by andreasschroth** [comment]
Also important for us - monthly invoices are always a hassle and the more services and companies you use, the more invoices there are. We would love to see having 1 invoice per year instead of 12. I think it's also in the commercial interests of Docker Inc. (less payment fees, less hassle, less support, ...).

**Comment by andreasschroth** [comment]
Not needed for us anymore as we switched away from Docker Hub. The new pricing is a joke.

**Comment by makimat** [comment]
Is this anywhere on the backlog?
