### ISSUE TITLE
Link to activate account expired

### ISSUE THREAD

**Issue by bonczo** [docker/hub-feedback#1243]
After three days I realized that my link to activate account is in junk email. This link is expired. How can I get new fresh link to activate account?

**Comment by jasonandrewduncan** [comment]
I have the same issue, I even went through password reset hoping to fix this issue.. I was able to reset my password; which sent an link to my email.. which indirectly confirms my email as good; but my account is still locked (not active) because I didn't use my initial confirmation link within 2 days; so now I'm stuck without a valid docker hub account and no way to fix it for my email.
