### ISSUE TITLE
s3 bucket for docker hub images

### ISSUE THREAD

**Issue by venutm** [docker/hub-feedback#1318]
I have a restricted docker hub repo to which I am able to login.
But when I try to download images I get the errro:
error pulling image configuration: error parsing HTTP 403 response body: invalid character '<' looking for beginning of value: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>AccessDenied</Code><Message>Access Denied</Message><....

I believe this error is coming because my security prolicy restricts download from random s3 buckets. 
Would it be possible to know the s3 bucket name so that I can add it to my VPC policy.

**Comment by SpiderX** [comment]
I am interested in such information too.

**Comment by SpiderX** [comment]
At least part of Docker Hub infrastructure uses AWS S3.
Most likely this part is responsible for requests to Docker Hub that origin from AWS.

And here we run into a problem.

[VPC Endpoint](https://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/vpc-endpoints.html) is often used to connect AWS S3 from VPC.
VPC Endpoint is a preferable solution to connect to AWS services outside of VPC, because:
- it provides an additional level of security (it has its own policy)
- it reduces the cost of ownership (for example, traffic that origins in private subnet passing through the VPC Endpoint goes directly to S3 bypassing the NAT gateway)

In order to use VPC Endpoint with VPC Endpoint policy, you need to list names of S3 buckets in it.
The Docker Hub does not provide names of S3 buckets it currently uses, so there is no way to use Docker Hub together with policy-enabled VPC endpoint.
Please provide names of S3 buckets used by Docker Hub or provide a possibility to not use part of Docker Hub that relies on AWS infrastructure.

**Comment by SpiderX** [comment]
Any updates on this?

**Comment by SpiderX** [comment]
Any updates on this?

**Comment by makegofast** [comment]
docker-images-prod

`{
    "Version": "...",
    "Id": "...",
    "Statement": [
        {
            "Sid": "stmtAllowDockerImages",
            "Effect": "Allow",
            "Principal": "*",
            "Action": "*",
            "Resource": [
                "arn:aws:s3:::docker-images-prod",
                "arn:aws:s3:::docker-images-prod/*"
            ]
        }
    ]
}`
