### ISSUE TITLE
Changing UCP IP Address

### ISSUE THREAD

**Issue by timbure96** [docker/hub-feedback#1368]
Hello, 

I installed docker UCP with the following command:
docker container run --rm -it --name ucp \
  -v /var/run/docker.sock:/var/run/docker.sock \
  docker/ucp:2.2.5 install \
  --host-address 10.1.1.164 \
  --interactive \ --disable-tracking \ 

I've moved the server to a different subnet, 192.168.2.x  Now the UCP won't start, assuming it's because it's a different IP Address than when I installed it.  

Does anyone know how to change the --host-address config fof UCP once UCP is already installed? 
Thank you!

**Comment by zaggash** [comment]
Hi @timbure96,

Do you have a EE licence ? if yes, please open a case on suport.docker.com.

Otherwise, you are not in the right repo to open this kind of issue.
Please go to the Forum, you will find better answers.

Quick answer tho, you can try a : 
```
docker container run --rm -it --name ucp 
-v /var/run/docker.sock:/var/run/docker.sock 
docker/ucp:2.2.5 upgrade 
--host-address NEW_IP 
--interactive
```

But i you changed to a new subnet you swarm must have an issue too.
You'll need to `docker swarm init --force-new-cluster` and add your managers, worker back to the cluster.

**Comment by timbure96** [comment]
Thank you for replying. Accounting is currently purchasing the EE license.  I can def open a ticket with them when they finish.  I was just trying to get ahead of the issue and maybe figure it out before then :) 

I ran the command but i can't tell what happened because my stupid SSH timed out while it was working.

**Comment by zaggash** [comment]
you are not in the good repo for the issue too.
Here its dockerhub :/
