### ISSUE TITLE
Uninstall docker-owncloud installation & restart

### ISSUE THREAD

**Issue by jrpmedia** [docker/hub-feedback#1407]
I have installed owncloud on docker [MacOSX] badly;
- wrong database choice at setup, 
- wrong port after-thought :-(

How can I wipe my owncloud docker install and start again please?

_Thanks_,

**Comment by nandhini915** [comment]
Closing this ticket since it relates to running a container in a user's local environment or on the users on-prem/cloud based cluster. 
1. If you are a community user using our Docker Engine product, Please go to https://forums.docker.com/ and verify if other members in the community have run into this issue, or post an issue back to the community.
2. If you are a user with a subscription to Docker Enterprise, you can go to https://success.docker.com/ and obtain help.
