### ISSUE TITLE
Docker Event API is not responding 

### ISSUE THREAD

**Issue by Deyvasigamani** [docker/hub-feedback#1421]
I am calling below docker event API 
/v1.24/events?since=1521009690 , i am not getting any response from server, When i do curl for the same I am getting response but the connection is still open it is not getting closed.

**Comment by nandhini915** [comment]
Closing this ticket since it relates to running a container in a user's local environment or on the users on-prem/cloud based cluster. 
1. If you are a community user using our Docker Engine product, Please go to https://forums.docker.com/ and verify if other members in the community have run into this issue, or post an issue back to the community.
2. If you are a user with a subscription to Docker Enterprise, you can go to https://success.docker.com/ and obtain help.
