### ISSUE TITLE
Create Docker Images for Debian Packages files

### ISSUE THREAD

**Issue by naveencherukuru** [docker/hub-feedback#1422]
Hi ,

I have created a Deb Packages . Now I need to create a docker image for those files . Any pointers will be greatly appreciated. These are the type of files that were generated 

.buildinfo
.changes
.deb
.ddeb 
.tar.xz

Thanks,
N

**Comment by nandhini915** [comment]
Closing this ticket since it relates to running a container in a user's local environment or on the users on-prem/cloud based cluster. 
1. If you are a community user using our Docker Engine product, Please go to https://forums.docker.com/ and verify if other members in the community have run into this issue, or post an issue back to the community.
2. If you are a user with a subscription to Docker Enterprise, you can go to https://success.docker.com/ and obtain help.
