### ISSUE TITLE
Builds on hub not supporting ADD & chown

### ISSUE THREAD

**Issue by setiseta** [docker/hub-feedback#1427]
In Dockerfile reference on the 'add' section is an optional flag chown:
https://docs.docker.com/engine/reference/builder/#add

If I use this and push the file to be automated build on dockerhub, its failing with:
Step 5/11 : ADD --chown=1000:1000 node /node
Unknown flag: chown

Build Link:
https://hub.docker.com/r/kyberna/tomcat/builds/bbczhjfedtr33esxmg795zw/

**Comment by thaJeztah** [comment]
The `--chown` option was added through https://github.com/moby/moby/pull/34263, which is in Docker 17.09 and up (I think), but it looks like the nodes for automated builds run 17.06;

```
Building in Docker Cloud's infrastructure...
Cloning into '.'...

KernelVersion: 4.4.0-93-generic
Arch: amd64
BuildTime: 2017-08-17T22:50:04.828747906+00:00
ApiVersion: 1.30
Version: 17.06.1-ce
MinAPIVersion: 1.12
GitCommit: 874a737
Os: linux
GoVersion: go1.8.3
Starting build of index.docker.io/kyberna/tomcat:8-jre8-alpine...
```

**Comment by setiseta** [comment]
oh thank you for the information. I haven't checked the versions.
any informations on update plans on these nodes?

**Comment by thaJeztah** [comment]
I don't have that information (I'm not part of the Docker Hub / Docker Cloud team), but opened an issue internally to check if this is planned

**Comment by pitpit** [comment]
`--chown` still not supported (docker version: 17.06.1-ce)

Could we have a feedback from the Dockerhub team about when Docker  used in Automated builds will be updated to a more recent version ?

**Comment by syedhassaanahmed** [comment]
+1 My build is failing because of this

**Comment by lsl** [comment]
@thaJeztah Further feedback or even an ETA would be great.

**Comment by itsagoodbrain** [comment]
Agreed that feedback would be great, but given we haven't heard from anyone on the Docker Hub team I'm going to put down a few options and see where they go.
1. @thaJeztah Do you think we could add a line mentioning the current build nodes version on https://docs.docker.com/docker-hub/builds/#limitations so it is more obvious to people what features they can and can't use for automated builds? We could get fancy with some type of list of features that have been introduced since then, but I think people can look it up on their own when they're using features.
2. I'm starting a feature-request #1511 that would hopefully prevent this from continuing to occur. If other people have better ideas or contributions to that, please feel free to jump on it.
3. Anyone with much more experience with the build system want to give some hacky work around involving docker in docker (dind) which is supported on dockerhub for quite a few versions. I toyed around with the idea, but didn't really know how to trigger it reasonably and make sure that the built image actually ends up being sent to the repo as intended. 
4. Another obvious work around is just not using the build automation... but this option is of course filled with sadness. <3 automation

**Comment by lsl** [comment]
@thaJeztah / @thread: This is fixed.

**Comment by itsagoodbrain** [comment]
Before closing... could we maybe get a yes or no about including some note somewhere in the docs of the version?
That way hopefully people won't need to dive into the issues threads to find out what version the builds are running.
