### ISSUE TITLE
Whether it can be implemented on Docker to create 2 instances on one VPS, pointing to the same domain name

### ISSUE THREAD

**Issue by PaulLee3xf** [docker/hub-feedback#1435]
For this domain name: www.example.com/index.html
Whether it can be implemented on Docker to create 2 instances on one VPS, pointing to the same domain name,but the index file created by the two instances is different. When the visitor satisfies the setting conditions, the results of the two layers are displayed (the upper results are displayed to the visitor). If the conditions are not met, then extract the top results (show lower results to the user)

**Comment by PaulLee3xf** [comment]
anyone can help me?

**Comment by nandhini915** [comment]
Closing this ticket since it relates to running a container in a user's local environment or on the users on-prem/cloud based cluster. 
1. If you are a community user using our Docker Engine product, Please go to https://forums.docker.com/ and verify if other members in the community have run into this issue, or post an issue back to the community.
2. If you are a user with a subscription to Docker Enterprise, you can go to https://success.docker.com/ and obtain help.
