### ISSUE TITLE
There is a problem with docker for windows, Can you help me?

### ISSUE THREAD

**Issue by qifei0708** [docker/hub-feedback#1443]
I am using docker for windows. I started my nginx container according to the demo of the document [docker run --rm -itd --network host --name my_nginx nginx] but I can't access it with http://localhost:80. This makes me very distressed. Can you help me?

**Comment by nandhini915** [comment]
Closing this ticket since it relates to running a container in a user's local environment or on the users on-prem/cloud based cluster. 
1. If you are a community user using our Docker Engine product, Please go to https://forums.docker.com/ and verify if other members in the community have run into this issue, or post an issue back to the community.
2. If you are a user with a subscription to Docker Enterprise, you can go to https://success.docker.com/ and obtain help.
