### ISSUE TITLE
File Name too long and container not able to created

### ISSUE THREAD

**Issue by amahuja25** [docker/hub-feedback#1447]
Creating dls-dps ... error

ERROR: for dls-dps  Cannot create container for service dps_integration: failed to read /mnt/sda1/var/lib/docker/aufs/mnt/bd97508cd3a455f6e9232ca06786f1a479165b44275e0d1f97501784ff37b5dc/etc/opt/models/etc/model/2018-04-02_23-00-29/dps_relationship/urn%3ardns%3acom%3aoammodel-pbr-ipos/ip-access-group%24%24class%24%24redirect-destination%24%24redirect-destination-choice%24%24ipv6%24%24next-hopfake-Router6672_ip-access-group%24%24class%24%24redirect-destination%24%24redirect-destination-choice%24%24ipv6_2016.12.29: 
lstat /mnt/sda1/var/lib/docker/aufs/mnt/bd97508cd3a455f6e9232ca06786f1a479165b44275e0d1f97501784ff37b5dc/etc/opt/models/etc/model/2018-04-02_23-00-29/dps_relationship/urn%3ardns%3acom%3aoammodel-pbr-ipos/ip-access-group%24%24class%24%24redirect-destination%24%24redirect-destination-choice%24%24ipv6%24%24next-hopfake-Router6672_ip-access-group%24%24class%24%24redirect-desti
nation%24%24redirect-destination-choice%24%24ipv6_2016.12.29/ip-access-group%24%24class%24%24redirect-destination%24%24redirect-destination-choice%24%24ipv6%24%24next-hopfake-Router6672_ip-access-group%24%24class%24%24redirect-destination%24%24redirect-destination-choice%24%24ipv6_2016.12.29-2016.12.29.xml: file name too long

ERROR: Encountered errors while bringing up the project.

**Comment by amahuja25** [comment]
using windows 7 machie.

**Comment by nandhini915** [comment]
Closing this ticket since it relates to running a container in a user's local environment or on the users on-prem/cloud based cluster. 
1. If you are a community user using our Docker Engine product, Please go to https://forums.docker.com/ and verify if other members in the community have run into this issue, or post an issue back to the community.
2. If you are a user with a subscription to Docker Enterprise, you can go to https://success.docker.com/ and obtain help.
