### ISSUE TITLE
Image asdnf/grapesjs

### ISSUE THREAD

**Issue by alessandroalb** [docker/hub-feedback#1458]
I have pull this image on my desktop, but nothing info how to run and use it.
Someone have some info for this ?
Ty

**Comment by nandhini915** [comment]
Closing this ticket since it relates to running a container in a user's local environment or on the users on-prem/cloud based cluster. 
1. If you are a community user using our Docker Engine product, Please go to https://forums.docker.com/ and verify if other members in the community have run into this issue, or post an issue back to the community.
2. If you are a user with a subscription to Docker Enterprise, you can go to https://success.docker.com/ and obtain help.
