### ISSUE TITLE
When is docker.for.mac.host.internal set?

### ISSUE THREAD

**Issue by wnm3** [docker/hub-feedback#1472]
I'm assuming docker.for.mac.host.internal is set when you run the docker image and remains static. The usecase is, I am in a building on campus and run my docker image, creating a container. If I test a database connection back to MySQL running on the host machine by using docker.for.mac.host.internal as the hostname it works fine. If I then walk to another building and get a different IP address assigned because the network has changed, will docker.for.mac.host.internal update automatically, or would I need to stop and rerun the image? E.g., is there some monitoring of the network configuration to automatically update the dns entry when the host's IP address changes.

**Comment by nandhini915** [comment]
Closing this ticket since it relates to running a container in a user's local environment or on the users on-prem/cloud based cluster. 
1. If you are a community user using our Docker Engine product, Please go to https://forums.docker.com/ and verify if other members in the community have run into this issue, or post an issue back to the community.
2. If you are a user with a subscription to Docker Enterprise, you can go to https://success.docker.com/ and obtain help.
