### ISSUE TITLE
Unable to install in Ubuntu

### ISSUE THREAD

**Issue by ZnaeW** [docker/hub-feedback#1475]
Hello,

I was trying to install Docker EE and got an error in the step of installing "sudo apt-get". I'm working with Ubuntu 17

```
sudo apt-get update
Ign:1 http://dl.google.com/linux/chrome/deb stable InRelease
Obj:2 http://dl.google.com/linux/chrome/deb stable Release                     
Des:4 http://security.ubuntu.com/ubuntu artful-security InRelease [83,2 kB]    
Obj:5 http://cl.archive.ubuntu.com/ubuntu artful InRelease                     
Obj:6 http://cl.archive.ubuntu.com/ubuntu artful-updates InRelease             
Obj:7 https://deb.nodesource.com/node_10.x artful InRelease                    
Des:8 http://cl.archive.ubuntu.com/ubuntu artful-backports InRelease [74,6 kB] 
Ign:9 https://storebits.docker.com/ee/ubuntu/sub-e3ad7008-de2d-44aa-9698-c698bd365c96/ubuntu artful InRelease
Obj:10 http://archive.ubuntu.com/ubuntu artful InRelease                       
Err:11 https://storebits.docker.com/ee/ubuntu/sub-e3ad7008-de2d-44aa-9698-c698bd365c96/ubuntu artful Release
  404  Not Found [IP: 52.84.177.152 443])
```

Please, tell me how I can fix it. I tried to follow some relative answers at stackoverflow.com without a good result :(

**Comment by nandhini915** [comment]
Closing this ticket since it relates to running a container in a user's local environment or on the users on-prem/cloud based cluster. 
1. If you are a community user using our Docker Engine product, Please go to https://forums.docker.com/ and verify if other members in the community have run into this issue, or post an issue back to the community.
2. If you are a user with a subscription to Docker Enterprise, you can go to https://success.docker.com/ and obtain help.
