### ISSUE TITLE
permission denied for Cacti real time graphs

### ISSUE THREAD

**Issue by logendrae** [docker/hub-feedback#1478]
Hi All,

I'm new to docker, and recently i've installed cacti on docker and the graphs are generated successfully, but when i opened the real time graph,  permission denied error message popped up. 

Appreciate you help to solve this issue.

Thanks,
Logendra

**Comment by nandhini915** [comment]
Closing this ticket since it relates to running a container in a user's local environment or on the users on-prem/cloud based cluster. 
1. If you are a community user using our Docker Engine product, Please go to https://forums.docker.com/ and verify if other members in the community have run into this issue, or post an issue back to the community.
2. If you are a user with a subscription to Docker Enterprise, you can go to https://success.docker.com/ and obtain help.
