### ISSUE TITLE
CentOS 7.4 (core) container running on CentOS 7.4 (core) machine not resolving host names

### ISSUE THREAD

**Issue by rraskin** [docker/hub-feedback#1488]
I hope this is an easy fix.

I downloaded the official centos image from Docker Hub. This is CentOS 7.4 (core). I have it running on a Linux machine also running CentOS 7.4 (core). The problem is the centos container can ping by IP address but not by hostname. The Linux host can ping hostnames.

Also, the same centos container CAN resolve hostnames when running under Docker Toolbox on my Windows 7 machine.

Any idea? My windows box is just for my own playing around, not for production.

**Comment by nandhini915** [comment]
Closing this ticket since it relates to running a container in a user's local environment or on the users on-prem/cloud based cluster. 
1. If you are a community user using our Docker Engine product, Please go to https://forums.docker.com/ and verify if other members in the community have run into this issue, or post an issue back to the community.
2. If you are a user with a subscription to Docker Enterprise, you can go to https://success.docker.com/ and obtain help.
