### ISSUE TITLE
Cannot login to Docker CE

### ISSUE THREAD

**Issue by wandonye** [docker/hub-feedback#1500]
Version 18.03.0-ce-mac60 (23751)

I cannot login with my id and password, which works well if I login from the website (hub.docker.com)

**Comment by r1ckr** [comment]
I can't `docker login` using my ID and API Key, but using my regular password it works

**Comment by nandhini915** [comment]
Closing this ticket since it relates to running a container in a user's local environment or on the users on-prem/cloud based cluster. 
1. If you are a community user using our Docker Engine product, Please go to https://forums.docker.com/ and verify if other members in the community have run into this issue, or post an issue back to the community.
2. If you are a user with a subscription to Docker Enterprise, you can go to https://success.docker.com/ and obtain help.
