### ISSUE TITLE
weblogic migration to docker container with applications

### ISSUE THREAD

**Issue by ai45242** [docker/hub-feedback#1509]
Hi Team,

I have a scenario like we had weblogic server running on linux which contains applications.
I want to push the weblogic as image to docker including servises.

Thanks,
AI45242.

**Comment by nandhini915** [comment]
Closing this ticket since it relates to running a container in a user's local environment or on the users on-prem/cloud based cluster. 
1. If you are a community user using our Docker Engine product, Please go to https://forums.docker.com/ and verify if other members in the community have run into this issue, or post an issue back to the community.
2. If you are a user with a subscription to Docker Enterprise, you can go to https://success.docker.com/ and obtain help.
