### ISSUE TITLE
Docker Toolbox on Windows PC: Error response from daemon: invalid mode: /root/docker

### ISSUE THREAD

**Issue by randommarko** [docker/hub-feedback#1513]
I am a Docker newbie and currently replicating course videos. I have to add that I only have Windows 10 Home and I am hence limited to Docker Toolbox. (At work I have W 10 Pro and use Docker itself and didnt experience the problem I am about to report). 

When I run fhe folloing in the Power shell: 

PS C:\Program Files\Docker Toolbox> docker run -ti -h python -v ${pwd}:/root/docker -p 9999:9999 ubuntu:latest /bin/bash

I get the following error

    C:\Program Files\Docker Toolbox\docker.exe: Error response from daemon: invalid mode: /root/docker.
       See 'C:\Program Files\Docker Toolbox\docker.exe run --help'.

It works find in the command prompt, seems to be related to the Power Shell
I did not find anything in discussion boards. Any input would be appreciated.

Best
Markus

**Comment by nandhini915** [comment]
Closing this ticket since it relates to running a container in a user's local environment or on the users on-prem/cloud based cluster. 
1. If you are a community user using our Docker Engine product, Please go to https://forums.docker.com/ and verify if other members in the community have run into this issue, or post an issue back to the community.
2. If you are a user with a subscription to Docker Enterprise, you can go to https://success.docker.com/ and obtain help.
