### ISSUE TITLE
microsoft/aspnet image on Linux container

### ISSUE THREAD

**Issue by gurvinder1129** [docker/hub-feedback#1517]
Is there any way to use [aspnet docker image](https://hub.docker.com/r/microsoft/aspnet) in linux container.
I want to run Aspnet web application on Linux container.
I think only[ .net core](https://hub.docker.com/r/microsoft/aspnetcore) apps are supported on Linux container , not the Aspnet Apps

**Comment by nandhini915** [comment]
Closing this ticket since it relates to running a container in a user's local environment or on the users on-prem/cloud based cluster. 
1. If you are a community user using our Docker Engine product, Please go to https://forums.docker.com/ and verify if other members in the community have run into this issue, or post an issue back to the community.
2. If you are a user with a subscription to Docker Enterprise, you can go to https://success.docker.com/ and obtain help.
