### ISSUE TITLE
Very new to Docker. Need Help

### ISSUE THREAD

**Issue by rudyrana** [docker/hub-feedback#1530]
I am fairly new to Docker and am trying to BUILD my first Docker Container. I want to create a container of Apache, MySQL, and PHP that is installed on a MAC because I wish to test this combination for a very specific reason on another Linux system. I was reading online and therein it mentioned that I will need to install Packages and Start the Services for Apache, MySQL, and PHP.
Apache and PHP are already pre-installed in a MAC; I will just need to install MySQL and configure the "htdocs" to my specific requirements.
Do I need to use Dockerfile or Docker-compose for what I need to do? How can I do this and create a Container?

**Comment by nandhini915** [comment]
Closing this ticket since it relates to running a container in a user's local environment or on the users on-prem/cloud based cluster.

1. If you are a community user using our Docker Engine product, Please go to https://forums.docker.com/ and verify if other members in the community have run into this issue, or post an issue back to the community.
2. If you are a user with a subscription to Docker Enterprise, you can go to https://success.docker.com/ and obtain help.
