### ISSUE TITLE
Unable to login on CLI using docker login

### ISSUE THREAD

**Issue by IshaanBhatnagar-IB** [docker/hub-feedback#1540]
![screenshot from 2018-06-20 16-40-10](https://user-images.githubusercontent.com/26304605/41654972-c07c1682-74a8-11e8-98b5-d8bb5974a105.png)
I am using Ubuntu 18.04 and unable to login to my docker account.
It is showing:
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.35/auth: dial unix /var/run/docker.sock: connect: permission denied
Fix?

**Comment by nandhini915** [comment]
Closing this ticket since it relates to running a container in a user's local environment or on the users on-prem/cloud based cluster.

If you are a community user using our Docker Engine product, Please go to https://forums.docker.com/ and verify if other members in the community have run into this issue, or post an issue back to the community.
If you are a user with a subscription to Docker Enterprise, you can go to https://success.docker.com/ and obtain help.
