### ISSUE TITLE
Docker With Symfony

### ISSUE THREAD

**Issue by samanshahzadi** [docker/hub-feedback#1551]
I am running the following commands, and it is returning errors
$ winpty docker-compose exec PHP composer install
Composer could not find a composer.json file in /var/www/Symfony
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section

Not:: This I downloaded the repository from git and trying to set up locally.

Abrupt Response will be appreciated.

Thank you

**Comment by nandhini915** [comment]
Closing this ticket since it relates to running a container in a user's local environment or on the users on-prem/cloud based cluster. 
1. If you are a community user using our Docker Engine product, Please go to https://forums.docker.com/ and verify if other members in the community have run into this issue, or post an issue back to the community.
2. If you are a user with a subscription to Docker Enterprise, you can go to https://success.docker.com/ and obtain help.
