### ISSUE TITLE
Expose embedded DNS server to host

### ISSUE THREAD

**Issue by eugene-bright** [docker/hub-feedback#1558]
I look for easy way for accessing containers by it's name from host.
Does someone know how to easily access docker embedded DNS server from the host? It listens on address `127.0.0.11` in every container.

**Comment by eugene-bright** [comment]
I'm not the only one who straggles with it.
https://stackoverflow.com/questions/39070547/how-to-expose-a-docker-network-to-the-host-machine

**Comment by nandhini915** [comment]
Closing this ticket since it relates to running a container in a user's local environment or on the users on-prem/cloud based cluster. 
1. If you are a community user using our Docker Engine product, Please go to https://forums.docker.com/ and verify if other members in the community have run into this issue, or post an issue back to the community.
2. If you are a user with a subscription to Docker Enterprise, you can go to https://success.docker.com/ and obtain help.

**Comment by PaoJiao** [comment]
[this answer](https://stackoverflow.com/a/39730558) does helped me. 

from google.

**Comment by PaoJiao** [comment]
[this answer](https://stackoverflow.com/a/39730558) helped me out.

from google.
