### ISSUE TITLE
automatic build fails with "Unexpected Error" with no logs available - Dockerfile fine building manually

### ISSUE THREAD

**Issue by mavelli** [docker/hub-feedback#1564]
i did some slight adjustments to a Dockerfile, which is linked into being automatically built on dockerhub

https://hub.docker.com/r/mavelli/rocker-bayesian/builds/

unfortunately, the automatic build fails and the result is "Unexpected Error" without any logs as output.

the Dockerfile itself works fine if i build it manually

**Comment by PhoenixPeca** [comment]
Im experiencing the issue as well. @mavelli has this intermittent error been happening since 2 years ago?
![image](https://user-images.githubusercontent.com/9730242/88817862-9f1c2700-d1f0-11ea-9d50-898f99b329bf.png)

---

Often-time, I get build failing errors.. But whenever I try to rebuild (without changes from git) it works (sometimes). Not sure what's happening here. can somebody enlighten me?
