### ISSUE TITLE
can't connect to msql

### ISSUE THREAD

**Issue by ajulio4** [docker/hub-feedback#1567]
I just buy my MAS OS and i installed docker, i pull the mysql image and run it. i want to connect to mysql container via mysql workbench but i have connection failed. please can you help me?

**Comment by nandhini915** [comment]
Closing this ticket since it relates to running a container in a user's local environment or on the users on-prem/cloud based cluster. 
1. If you are a community user using our Docker Engine product, Please go to https://forums.docker.com/ and verify if other members in the community have run into this issue, or post an issue back to the community.
2. If you are a user with a subscription to Docker Enterprise, you can go to https://success.docker.com/ and obtain help.
