### ISSUE TITLE
Best supported Docker version and Linux version for IBM Power 9 system.

### ISSUE THREAD

**Issue by balagalin** [docker/hub-feedback#1569]
Hi,

We want to install docker on a Linux version on IBMi Power 9 system (AS400 box) hardware. For this need to do partition of our Power9 system and install a Linux version. On top of it we need to install Docker and have a application in a container. The idea is to communicate from our AS400 box to the application on Docker container installed on same but partitioned hardware of AS400 box. So please let us know which Versions of Docker and Linux are best supported to install on our Power 9 system ( AS400 box) for a smooth and hassle- free communication between them.

**Comment by nandhini915** [comment]
Closing this ticket since it relates to running a container in a user's local environment or on the users on-prem/cloud based cluster. Please check out https://docs.docker.com/ee/supported-platforms/#supported-platforms to get a list of verified OSes for IBM Power.
 
1. If you are a community user using our Docker Engine product, Please go to https://forums.docker.com/ and verify if other members in the community have run into this issue, or post an issue back to the community.
2. If you are a user with a subscription to Docker Enterprise, you can go to https://success.docker.com/ and obtain help.

**Comment by f2ka07** [comment]
I will go for Ubuntu. First, Ubuntu has a large and active community that provides extensive documentation, support, and updates. This makes it easier for users to troubleshoot issues, find solutions to common problems, and stay up-to-date with the latest developments. Additionally, Ubuntu has a strong focus on security, which is crucial for running containers in a production environment. It also has a wide range of pre-built images available on Docker Hub, making it easier for users to get started with Docker and deploy containers quickly. Finally, Ubuntu's package manager, APT, is easy to use and allows for seamless installation and management of Docker and other dependencies.  These factors make Ubuntu the [best Linux Distro for running Docker](https://solid-future.com/docs/best-operating-system-linux-distro-docker/) and other [containerized applications](https://www.solid-future.com).
