### ISSUE TITLE
How to edit the source project for automated builds (or delete its build history)?

### ISSUE THREAD

**Issue by mkjsix** [docker/hub-feedback#1727]
## Problem description

We must change or remove the source project for automated builds of our [Docker repository](https://cloud.docker.com/repository/docker/softinstigate/restheart), as it now points to a deleted Github repository. We still can't find a way to do this. Deleting and recreating the repository on Docker Hub is not an option, as we would lose the downloads history and we have too many tags.

The build settings doesn't show any edit or delete option. It's critical for us, as we'd like to move to an official image but this step is preventing us to move forward.

As we don't actually need the automated builds (we are using Travis-CI for that), it would be just enough to delete or hide this old Github repo and its build history.

<img width="1140" alt="schermata 2018-12-18 alle 20 15 34" src="https://user-images.githubusercontent.com/365382/50527347-f8d5e000-0ae7-11e9-9aff-e61b01282a9d.png">

**Comment by meticulous-dft** [comment]
Hey @mkjsix I am trying to understand what you need here. 

Since the build is not active (the checkbox is not checked in the ui), you can just treat it as a normal repository without auto build.

Seems like you want Dockerfile, the source repo and build history not shown up here https://hub.docker.com/r/softinstigate/restheart since the build is inactive? 

Only users belong to the organization can see the build settings page. So I assume you are ok it is still there.

**Comment by meticulous-dft** [comment]
Got it. I will work on a fix for this, and will post updates here. Sorry for the inconvenience.
