### ISSUE TITLE
BuildSystem - Unexpected File Pathes when dockerfile is in subdirectory

### ISSUE THREAD

**Issue by BoasE** [docker/hub-feedback#1728]
## Problem description
I've a docker file in this location:  ```src/Dockerfile.build```

In the bild i paste this path as dockerfile. I leave the buildcontext empty.

As a results the files are not in the place i expect them to be. e.g.  there is a file ```src/cContexts/Runtimes/RocketSchool.Api/Api.csproj```

I can see that the correct dockerfile is found and executed by the buildsystem, but I got exceptions indicating that the api.csproj is not found.

When I run the docker file locally everything builds fine
I assume its related to the subpath the dockerfile is placed in?

The config in the build portal looks like this
![image](https://user-images.githubusercontent.com/4619513/50540774-3c882280-0b98-11e9-8b73-24253073998c.png)

My Docker file looks like this:

```
FROM microsoft/dotnet:2.2-sdk AS builder
WORKDIR /
COPY . .
RUN dotnet restore Contexts/Runtimes/RocketSchool.Api/Api.csproj
RUN dotnet publish Contexts/Runtimes/RocketSchool.Api/Api.csproj -o /dockerout/ -c Release


FROM microsoft/dotnet:2.2-aspnetcore-runtime
WORKDIR /app
EXPOSE 80 5000

COPY --from=builder /dockerout .

ENTRYPOINT ["dotnet", "Api.dll"]`
```
Is there an example on how to handle docker files in subdirectories ? What am I missing?

**Comment by meticulous-dft** [comment]
Hey @BoasE Since the context is at root (parent of src), i expect the file would be `src/Contexts/Runtimes/RocketSchool.Api/Api.csproj` in the build system.

You can check the section `Set the build context and Dockerfile location` in https://docs.docker.com/docker-hub/builds/#set-the-build-context-and-dockerfile-location for more info.

I guess you want to set context to /src in this case?
