### ISSUE TITLE
No link to Dockerfile with custom Dockerfile name in automated build

### ISSUE THREAD

**Issue by andaag** [docker/hub-feedback#1735]
## Problem description
https://hub.docker.com/r/andaag/aibox_cuda9

This is built with a Dockerfile using automated builds, however, it's not showing the Dockerfile in the UI. Maybe because it's using a custom Dockerfile name?

I think this is a serious issue, because I'd personally not use any image that isn't automatically built. Manually built images immediately looses a lot of credibility with me, as they look less secure/less professionally done.
   
Possibly related to https://github.com/docker/hub-feedback/issues/268, but probably not, since automated builds worked fundamentally differently at that time. (And those old builds I have still link properly to the Dockerfile..)

**Comment by meticulous-dft** [comment]
It is probably related to #1732. Will investigate if this is not the case.

**Comment by darkmattercoder** [comment]
In #1732 there was a similar comment about whether one could get a `Dockerfile` tab on dockerhub, even when the build automation is done using a CI/CD tool somewhere else: https://github.com/docker/hub-feedback/issues/1732#issuecomment-453245548

I assumed that in my repo (that one I referred to in #1732) there is no `Dockerfile` linked because I override `build` and `push` via hooks, while the build and push is done from a different CI/CD-service. 

But since the automated build itself is enabled and the `README.md` is successfully pulled out of the github repo, I wonder whether we can have the dockerfile link there as well.

**Comment by anentropic** [comment]
I have a similar issue

I originally built my project using dockerhub automated builds linked to github

Then I changed to building in github actions and pushing from there, primarily as I wanted to build a multi-arch image using buildx (also I wanted dockerhub to use a different readme from the main github repo...)

Now my "Dockerfile" tab is stuck showing the old version of the Dockerfile from last time I did an auto build on dockerhub 😞 

I would like to be able to remove the outdated Dockerfile tab

And ideally it would be possible for dockerhub to still sync the Dockerfile content when github repo is linked, but when new externally-built image tags are pushed.

**Comment by anentropic** [comment]
well, I can see why dockerhub wouldn't show Dockerfile content for externally-built image pushes... it has no way to verify which commit they were built from

but that also emphasises why the current situation is wrong

as soon as a push a new `latest` tag from an externally-built source, the Dockerfile tab content on dockerhub should disappear, since it is now inaccurate
