### ISSUE TITLE
Cannot cancel an In_Progress build

### ISSUE THREAD

**Issue by lshep** [docker/hub-feedback#1742]
I have read all the documentation and followed the instructions to go to the Timeline section that lists all builds including pending, in_progress, and build history. 

I can easily cancel a "pending" build as there is a button available for cancel in the far right next to Last updated (with a hover over that says cancelling a build may take some time)  -  but there seems no way to do this for an "in_progress" build.  I know a build is going to fail as I caught a mistake and I don't want to wait for it to finish but I don't get the cancel button on the right hand side for a build that has already started.

**Comment by meticulous-dft** [comment]
Hi, this is expected. Once a build is in progress we can not cancel it any more.

**Comment by lshep** [comment]
This seems like it would be a really good feature to have -  if a build takes hour or more to build and you know there was an error in the script its frustrating to have to wait for it to finish in order to correct.

**Comment by grahamlyons** [comment]
If this is expected behaviour then the documentation is wrong: https://docs.docker.com/docker-hub/builds/#cancel-or-retry-a-build. Note that this is for the new Docker hub builds and not the classic ones (https://docs.docker.com/docker-hub/builds/classic/).

I don't see cancel, retry, rebuild or logs for builds on the new Docker Hub; is that expected? Are we awaiting the features or have they just been removed?

**Comment by meticulous-dft** [comment]
Hi @grahamlyons I think the features are there as documentation described for the new auto build. Please let me know more details if you find something not working.

**Comment by lshep** [comment]
I agree the documentation is wrong  -  I do not get a Retry button in any location -  and as I pointed out there is no option to cancel a RUNNING build but the document worded it can be done.

**Comment by grahamlyons** [comment]
@meticulous-dft, I do see where the logs are now - I think there might have been an issue with permissions because I now see 7 tabs when previously I saw 4. I can't recreate that though.

I definitely don't get a 'Retry' button on failed builds.
<img width="1127" alt="screenshot 2019-02-12 at 22 59 34" src="https://user-images.githubusercontent.com/284688/52673912-f1448c00-2f19-11e9-84b6-e93d1a254e6c.png">

I get a JS error when I click on a build too: `Uncaught TypeError: Cannot read property 'build_results' of undefined` (timeline:61)
It takes me to the build when I click again.

**Comment by meticulous-dft** [comment]
@grahamlyons Not seeing all tabs are permission issue. There is some details here https://docs.docker.com/docker-hub/orgs/

From the snapshot, i think this is a repo using classic auto build. https://docs.docker.com/docker-hub/builds/classic/, you will see both the `builds` tab and `timeline` tab looks different from the docs in https://docs.docker.com/docker-hub/builds/

A simple way to tell is to go the `timeline` tab. For classic auto build, you will see table with rows. For the new build system, you will see expandable panels. 

Yes, we don't have the abilities to retry or cancel classic auto build. We are in the middle of migrating all legacy builds to the new build system, it would take some time. I expect both retry (build error) and cancel (not finished) would show up in the expandable panels.

**Comment by grahamlyons** [comment]
Aha. Thank you.
