### ISSUE TITLE
Greater-than symbol ">" is escaped to "&gt"

### ISSUE THREAD

**Issue by nwtgck** [docker/hub-feedback#1746]
## Problem description

As you can see a screenshot below, ">" is escaped to "&gt" in README in Docker Hub .

<img width="500" alt="screen shot 2019-01-30 at 0 28 28" src="https://user-images.githubusercontent.com/10933561/51919175-3a7ae300-2426-11e9-8157-3fdb6d13e2ea.png">

The actual repo can be found in
Docker Hub: https://hub.docker.com/r/nwtgck/piping-server
GitHub: https://github.com/nwtgck/piping-server
(The project is an automated build.)

**Comment by meticulous-dft** [comment]
Thanks for letting us know, will look into this.

**Comment by pedroferreira84** [comment]
Still regarding this problem, when the character ">" appears alone it seems that the problem is solved indeed. However, when there is text between the two characters "<...>" that text is omitted to the user.

In our project the following images show that problem:

https://hub.docker.com/r/pegi3s/bedtools/
https://hub.docker.com/r/pegi3s/blast/
https://hub.docker.com/r/pegi3s/emboss/
https://hub.docker.com/r/pegi3s/raxml/
https://hub.docker.com/r/pegi3s/sapp/
https://hub.docker.com/r/pegi3s/soapdenovo2
https://hub.docker.com/r/pegi3s/sratoolkit/
https://hub.docker.com/r/pegi3s/tcoffee/
https://hub.docker.com/r/pegi3s/utilities


Besides that, the character "&" isn't also being recognized by the new Docker Hub UI, like the following image shows:

https://hub.docker.com/r/pegi3s/afterqc/


Best,
Pedro.

**Comment by meticulous-dft** [comment]
@pedroferreira84 Should be fixed.

**Comment by pedroferreira84** [comment]
> @pedroferreira84 Should be fixed.

Thank you very much! The problem is solved! :)
