### ISSUE TITLE
delete manifests via registry api

### ISSUE THREAD

**Issue by cblomart** [docker/hub-feedback#1759]
## Problem description

I am building a opensource project with CI/CD.
Every commit is builded and pushed to docker hub with the short commit number as their tag.

I wanted to find a way to cleanup old commit builds but keep a few (i.e. last 15 days and at least 3). 

i.e. 
a little tool that would take a few argument:
- repository to run against
- regex match for tags
- days to keep
- minimum number of tags to keep

I looked at registry api against ```registry-1.docker.io```.  And i am able to list tags with details without any issues.
Delete manifests is apparently supported there.
doing a delete on ```https://registry-1.docker.io/v2/{repo}/maniftests/{digest}``` responds with:
```json
{"errors":[{"code":"UNSUPPORTED","message":"The operation is unsupported."}]}
```
From my reading of it, it seems that delete has not been disabled on the backend registry.

**Comment by manishtomar** [comment]
Delete has been disabled in hub registry. If needed please delete tag from Hub API `DELETE hub.docker.com/v2/repositories/{repo}/tags/{tag}`. You will authenticate though.

**Comment by manishtomar** [comment]
Closing as non-issue.

**Comment by cblomart** [comment]
Both api's apparently are protected by the same authenication/authorization mechanism but a specific api is needed for docker hub? 
For people making use of registries it sounds to me that generic tools and api looks better.

Could you elaborate on the reason not to trust delete at the registry api level?

**Comment by manishtomar** [comment]
Disabling delete was probably done before me but I am guessing it is because that API was getting implemented at that time. Blocking deletes is also safer as user could mistakenly called it. Deleting from Hub allows us to fine tune the delete. 

Note that although you are free to call registry APIs directly we do not guarantee that every registry API will be implemented. Our primary focus is to ensure it works seamlessly with Docker CLI.

**Comment by cblomart** [comment]
If operations needs to go trough:
hub.docker.com/v2/repositories/{repo}/tags/{tag}

A documentations of the API would be realy nice!
I am currently trying to get all tags via this api and the pagination does give me a headache.

**Comment by cblomart** [comment]
Btw the url that seem to work is not ```hub.docker.com/v2/repositories/{repo}/tags/{tag}``` but ```cloud.docker.com/v2/repositories/{repo}/tags/{tag}```

**Comment by cblomart** [comment]
Has anybody, by any means enabled delete on registry-1.docker.io ?
I worked yesterday evening and this morning to implement delete with cloud.docker.io ...
I check the whold thing back and now:

request:
```
DELETE https://registry-1.docker.io/v2/cblomart/vsphere-graphite/manifests/sha256:cbe2c27fdb7fe04908ec38b5b5cfa8aa4e0e5c45470ab9f6ff48723641ca2178
```

response headers
```
Www-Authenticate: Bearer realm="https://auth.docker.io/token",service="registry.docker.io",scope="repository:cblomart/vsphere-graphite:delete",error="insufficient_scope"
```

response content:
```
"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":[{"Type":"repository","Class":"","Name":"cblomart/vsphere-graphite","Action":"delete"}]}]}
```

I'll check if it works... thanks anyways (to someone or to luck)!

**Comment by ViBiOh** [comment]
I found this issue when trying to delete tags from the Docker registry instead of DockerHub.

If I curl the DockerHub API, I only have `latest` tag

```
$ curl "https://hub.docker.com/v2/repositories/vibioh/goweb/tags/?page_size=100"
{
  "count": 1,
  "next": null,
  "previous": null,
  "results": [
    {
      "images": [...],
      "name": "latest",
      "v2": true,
      "tag_status": "active"
    }
  ]
}
```

But if I do the same on the registry directly, I got much more answer

```
$ curl https://registry.docker.io/v2/vibioh/goweb/tags/list
{"name":"vibioh/goweb","tags":["02c7d13","037c0bf",[ 200 items ],"ff8a030","latest"]}
```

I was used to clean my repositories by using that query.

```
curl --request DELETE "hub.docker.com/v2/repositories/vibioh/goweb/tags/${tag}/"
```

When I saw that registry still contains the old tags, I tried to delete them with the manifest references but encountered the same issue than @cblomart .

Is this something expected?

My main point is that when using flux with image update automation, it founds tags that are still listed by the Docker Registry but not available from the DockerHub.
