### ISSUE TITLE
Build Failed : unauthorized: incorrect username or password

### ISSUE THREAD

**Issue by umersyed** [docker/hub-feedback#1763]
## Problem description
I am following the steps in : https://aws.amazon.com/getting-started/projects/break-monolith-app-microservices-ecs-docker-ec2/module-one/

Fails at step#4 , Build the Image: In the terminal, run docker build -t api 

Error:
Sending build context to Docker daemon  8.704kB
Step 1/6 : FROM mhart/alpine-node:7.10.1
Get https://registry-1.docker.io/v2/mhart/alpine-node/manifests/7.10.1: unauthorized: incorrect username or password

**Comment by nandhini915** [comment]
- If you are a community user using our Docker Engine product, Please go to https://forums.docker.com/ and verify if other members in the community have run into this issue, or post an issue back to the community. An alternative would be to see if users have run into this issue in AWS forums since you're pointing to an AWS how-to article.
