### ISSUE TITLE
Hide Dockerfile tab for projects that aren't autobuilt anymore

### ISSUE THREAD

**Issue by simonpasquier** [docker/hub-feedback#1847]
Follow-up of https://github.com/docker/hub-feedback/issues/1792

We've got more repositories that used to use autobuilds but not anymore. They still show the `Dockerfile` tab though.
https://hub.docker.com/r/prom/alertmanager
https://hub.docker.com/r/prom/blackbox-exporter
https://hub.docker.com/r/prom/busybox
https://hub.docker.com/r/prom/client-golang-examples-simple
https://hub.docker.com/r/prom/cloudwatch-exporter
https://hub.docker.com/r/prom/collectd_exporter
https://hub.docker.com/r/prom/consul-exporter
https://hub.docker.com/r/prom/graphite-exporter
https://hub.docker.com/r/prom/haproxy-exporter
https://hub.docker.com/r/prom/mysqld-exporter
https://hub.docker.com/r/prom/node-exporter
https://hub.docker.com/r/prom/prom2json
https://hub.docker.com/r/prom/pushgateway

**Comment by manishtomar** [comment]
Thanks for the report. We've created an internal ticket but it may not get addressed right away.

**Comment by simonpasquier** [comment]
No problem, thanks for the heads-up!

**Comment by simonpasquier** [comment]
Any update on this issue?

**Comment by simonpasquier** [comment]
:wave: still no news?

**Comment by DannyBen** [comment]
This is still an issue. Both the Dockerfile and the Builds tabs should be removed from repositories that no longer auto-build. Otherwise, this just makes these repositories look unmaintained, with old Dockerfile and last build "a year ago".

Also - the practice of having a bot close stale tickets is flawed, especially since it is stale not because of lack of interest, but because of lack of response...

**Comment by SebDanielsson** [comment]
Yeah, this is extremely annoying since it show a really old Dockerfile compared to the latest one.

**Comment by Simplatex** [comment]
Still an issue until now: posted here https://github.com/docker/hub-feedback/issues/2259
