### ISSUE TITLE
Pull command/checkout button not displaying for MCR images

### ISSUE THREAD

**Issue by JPZ13** [docker/hub-feedback#1866]
## Problem description
Hi hub team. I'm having to containerize a .NET application at my new job and saw that the pull command for .NET Framework isn't displaying. I've tested this out on Firefox and Chrome. 

A screenshot is below, and the url is https://hub.docker.com/_/microsoft-dotnet-framework
![Screen Shot 2019-08-14 at 1 28 11 PM](https://user-images.githubusercontent.com/6625432/63042723-9d9b0700-be98-11e9-97b3-875165c76d24.png)

In the console, there's an unhandled promise rejection that's not happening on other image pages.

Could y'all respond with the appropriate pull command for this image?

**Comment by JPZ13** [comment]
Heads up, this seems to be happening for all the Microsoft images right now

**Comment by JPZ13** [comment]
![Screen Shot 2019-08-14 at 2 06 18 PM](https://user-images.githubusercontent.com/6625432/63044676-b4dbf380-be9c-11e9-82d7-c60e2cd3cadf.png)

**Comment by olegburov** [comment]
Hi @JPZ13,

The repositories with .NET Framework and .NET Core that you pointed above are landing pages that points to featured repositories with specific .NET Runtimes or SDK. See **Description** tab. 
 
Since .NET covers many apps such as Web, Mobile, Desktop, Cloud, ML, IoT etc., you have to choose a specific image (and OS + Web Server such as IIS or Kestrel .

For example, if you containerizing a traditional Web App that is written in ASP.NET web framework (using .NET Framework), than you need those repos:

- .NET Framework:
   * For **building** app: https://hub.docker.com/_/microsoft-dotnet-framework-sdk/
   * For **running** app: https://hub.docker.com/_/microsoft-dotnet-framework-aspnet/

If you containerizing a modern Web App that is written in ASP.NET Core web framework (using .NET Core), than you need those repos:

- .NET Core:
   * For **building** app: https://hub.docker.com/_/microsoft-dotnet-core-sdk/
   * For **running** app: https://hub.docker.com/_/microsoft-dotnet-core-aspnet/

You can also list all tags from Microsoft registry using the following URLs:

- .NET Framework:
   * https://mcr.microsoft.com/v2/dotnet/framework/runtime/tags/list
   * https://mcr.microsoft.com/v2/dotnet/framework/sdk/tags/list

- .NET Core:
   * https://mcr.microsoft.com/v2/dotnet/core/aspnet/tags/list
   * https://mcr.microsoft.com/v2/dotnet/core/sdk/tags/list

**Comment by JPZ13** [comment]
Gotcha. Thanks, @olegburov!

**Comment by meticulous-dft** [comment]
Thanks for stopping by, and good luck in your new job 😄
