### ISSUE TITLE
Autofill login doesn't wor

### ISSUE THREAD

**Issue by thomassnielsen** [docker/hub-feedback#189]
Autofill of username and password doesn't work in Safari.

Related: #182 and #93 

Safari looks for ids ("username", "password" or similar) on the input elements to do this. The way it works is even more broken than I've seen elsewhere, as the fields seem to be filled, but they empty on submit, and a login error is shown. Also, the username/password labels than move on text field focus stay on top of the prefilled text.

![gif showing the bug](http://g.recordit.co/gksyj4vvJT.gif)

**Comment by AllYourBase** [comment]
My experience is identical to thomassnielsen's shown in his video above.

**Comment by nhsiehgit** [comment]
@AllYourBase Can you elaborate what browser you're using?

We've since removed the fancy input fields and i'm not able to reproduce this issue anymore.

**Comment by mro** [comment]
similar issue here, Brwoser doesn't fill in anything.

Safari Version 7.1.8 (9537.85.17.9.1), OSX 10.9.5

**Comment by JensErat** [comment]
Also broken with PasslFox (Firefox plugin for KeePass). This is very annoying. Typing a space and deleting it again (in both of the fields) solves the issue.

Might it be possible to copy the field's values to the internal duplicates again during input verification (at least if the internal representation is empty)?

Please, help us at keeping login secure by properly being able to use password managers instead of just having the same passphrase on all of the sites.
