### ISSUE TITLE
Personal access token feedback

### ISSUE THREAD

**Issue by mlamp** [docker/hub-feedback#1891]
_Originally posted by @meticulous-dft in https://github.com/docker/hub-feedback/issues/358#issuecomment-535692700_

So, tested it and I'm unsure why is this feature added at all? What it does is:
1. Adds another plain text login, you can use the same token for CLI and web, I would argue that one password would be better than having 2 or more, which those tokens seemed to be.
2. Introduced new attack vector, where baddy got hold of account owner password and silently (I didn't get email notification for docker hub) adds private access token which he can silently use, without user notice.
3. This new feature is pretty well hidden, so it is pretty hard to find if someone already used attack I just explained. At least for all the others, who even don't know there is a way to access your account without password.

**Comment by manishtomar** [comment]
Thank you for your feedback.

> 1. Adds another plain text login, you can use the same token for CLI and web, I would argue that one password would be better than having 2 or more, which those tokens seemed to be.

Access from web is blocked. We intended to add that before releasing but it got slipped. We've since implemented. Even from APIs (which are not officially supported) one cannot do admin operations like changing password adding email etc using token as password.

> 2\. Introduced new attack vector, where baddy got hold of account owner password and silently (I didn't get email notification for docker hub) adds private access token which he can silently use, without user notice.

Apologies this wasn't done. We are in the process of sending email when new token is added or deleted. This should roll out soon.

> 3\. This new feature is pretty well hidden, so it is pretty hard to find if someone already used attack I just explained. At least for all the others, who even don't know there is a way to access your account without password.

Thanks for your feedback. We will work internally to make this more visible.

The other advantages are:
- You need this to use it with CLI when your account has 2FA enabled (we will be launching this soon).
- You can inspect when it was last used and disable it if there is suspicious activity.
- It has limited scope if it gets leaked. As in one cannot change password or add email or do other admin activities using the token.

Let me know if you've any other concerns. I'll close this ticket.
