### ISSUE TITLE
[Feature Request] image "true"

### ISSUE THREAD

**Issue by lonix1** [docker/hub-feedback#1893]
There is a handy and highly popular image named `tianon/true`. Used in testing, deployment, etc.

There are already a number of official images, such as `hello-world`.

Please add this sort of image as `true`, and a corresponding one as `false`. It's easier to remember and use, without an organization name. And it's the sort of image that will never need to be updated.

**Comment by lonix1** [comment]
Still relevant today. Official `true` and `false` images are very useful, and would never need to be maintained.

**Comment by tianon** [comment]
This is very flattering. :smile:

I'm really curious, what is the use case for a `true` or `false` image?  Honestly, I've found `tianon/sleeping-beauty` more useful than `tianon/true` in practice (both were honestly created out of sheer "can we do this?" more than usefulness) -- I use `sleeping-beauty` for tricking Docker into thinking my volumes or networks are still "in use" so that I don't accidentally prune them. :joy:

If we go back in time in the `hello-world` image's history, we can see that it looks very familiar to anyone who has looked under the hood of `tianon/true`: https://github.com/docker-library/hello-world/blob/e968841b4ed61e28224e750cfbde6d77523f47aa/hello.asm (compare to https://github.com/tianon/dockerfiles/blob/eabfe1b9763dea0dfba4dae232c1633f27f9753e/true/true.asm), and that's very much not an accident. :smile:

Eventually, `hello-world` was re-written in C (https://github.com/docker-library/hello-world/pull/17) which increased the binary size a bit but meant it could more easily be supported across multiple architectures (although it took a little bit longer for that dream to become fully realized; https://github.com/docker-library/hello-world/pull/31).

We have a `busybox` image which is pretty small -- if you _really_ want/need a container which simply exits immediately, I would suggest that one (`docker run --rm busybox true` vs `docker run --rm busybox false` -- you can even get creative if you want some other specific exit code: `docker run --rm busybox sh -c 'exit 42'`).  That being said though, I'm still really confused what the use case is and would love some more details. :+1:

**Comment by lonix1** [comment]
To be honest I can't remember the use case! It was obvious to me until I tried to remember what it was and I can't. I searched my codebase but couldn't find it, so I must have replaced it with some workaround since then.

I think it was for data-only containers but there are workarounds.

It was also useful for compose file overrides, but now there's the "profiles" feature.

A container that exits immediately can be done with busybox, true (excude the pun), but it's easier with a "true" image instead. But using busybox is not so difficult as you pointed out.

@Skeen anything to add?
