### ISSUE TITLE
Can't find security scans on official images 

### ISSUE THREAD

**Issue by GodloveD** [docker/hub-feedback#1963]
According to [these docs](https://docs.docker.com/docker-hub/official_images/#official-image-vulnerability-scanning), I should be able to sign in and view scan results on official containers.  But I see no such results, even when I'm signed in.  Has this been silently moved to a paid feature or something?

**Comment by audgster** [comment]
Is there any update on this? We've been looking for the CVE scans as well.

**Comment by GodloveD** [comment]
Is this resolved?

**Comment by GodloveD** [comment]
...

**Comment by ingshtrom** [comment]
I know that this is an old thread but we do not provide public vulnerabilities for official images, right now. It seems we used to  in some form, but that was removed, as was the link @GodloveD originally pointed at no longer has the same anchor in the page. I have passed on this interest to our product teams. Thank you!

As a work-around you can official images locally with the `docker scan ...` command.

I am closing since as of this writing, we do no support public Vulnerability Scanning data for Official Images.
