### ISSUE TITLE
automated builds fail randomly since 2020-05-22 after a few seconds

### ISSUE THREAD

**Issue by erikmd** [docker/hub-feedback#1996]
## Problem description

My Docker Hub username is **`@erikmd`**. Since Friday 22 May 2020 @ 12:06 AM, I've noticed that most automated builds in  https://hub.docker.com/repository/docker/coq/coq/timeline now fail "after a few seconds", and the build logs tab just says "Logs are not available". See the screenshot below.
This is not specific to this repository, e.g. the last build of https://hub.docker.com/repository/docker/mathcomp/mathcomp/timeline (2020-05-24 @ 04:06 AM) also failed. Ideas on the origin of this issue?

![2020-05-24_10-45-37_Screenshot_Docker_Hub_automated-build_errors](https://user-images.githubusercontent.com/10367254/82749764-c4815480-9dab-11ea-9eeb-1aebff0da57d.png)

Best regards.

**Comment by Lukaesebrot** [comment]
Same for me.

**Comment by binhex** [comment]
yep me too, ongoing issue for around 5 days now, link to mine, failing build with no logs:-
https://registry.hub.docker.com/repository/registry-1.docker.io/binhex/arch-plex/builds/05867c62-e8d0-4a76-9e6c-cb4251d5acba

kicked it off again by clicking the retry button with NO code changes and it built:-
https://registry.hub.docker.com/repository/registry-1.docker.io/binhex/arch-plex/builds/8ed18986-d127-469b-8d87-6f41c82e9691

VERY frustrating, im getting a lot of failures due to this, i can only assume its due to infrastructure issues (aws?).

**Comment by RedactedProfile** [comment]
Thank you @binhex for this insight, This is my first ever connected dockerhub repo to github, and after two consecutive instantly failed attempts, I figured the problem was on my end, but nothing was really sticking out to me. 

After reading your message, i kicked off one more build and that one worked with no issues. 

Sounds to me like Dockerhubs's systems are getting exhausted which is triggering random build failures more often than not, but I genuinely don't know what the problem would be

**Comment by nevrending** [comment]
+1 This also happens on our part
As we have 50+ repos on Docker Hub, there will always be around 10 instant failures on every push. Thus this has been painful to manage

**Comment by binhex** [comment]
FYI i have also posted this on the 'Docker Community forum' as this repo to try and get some attention to the issue, feel free to +1.

https://forums.docker.com/t/random-automated-builds-fail-with-no-logs-available/94629

**Comment by manishtomar** [comment]
Thanks for the report. We are investigating and report back when we've an update.

**Comment by manishtomar** [comment]
We've fixed this internally. Apologies for the inconvenience. I am closing this ticket for now. Please feel free to reopen if you continue to see increased errors.
