### ISSUE TITLE
As authetnicated user I'm still geting error "too many requests"

### ISSUE THREAD

**Issue by nittools** [docker/hub-feedback#2040]
Hi,
I've recently bought "pro" plan, but sometimes I am still getting response code "too many requests" for image pulling.
What can be a reason of that? How to deal with that?
Are there any other limits for "pro" plan?

thanks

**Comment by binman-docker** [comment]
Hi @nittools - can you paste the full error message? There are two limits related to Hub - one specifically for pulls, and one that protects the infrastructure from being overloaded / DoS'd. You might be hitting the latter.

**Comment by nittools** [comment]
Hi

Today we're getting lots of errors like this:

2020-10-23 14:21:57,707 [http-nio-8081-exec-253] [ERROR] (o.a.a.d.r.v.DockerV2RemoteRepoHandler:469) - Unable to create manifest markers for 'docker-remote:library/redmine/sha256__991c3847972deff8d8318f971783966066afbc39e6f6a2144f8a9a168b242f58/manifest.json': 'Error fetching https://registry-1.docker.io/v2/library/redmine/manifests/sha256:991c3847972deff8d8318f971783966066afbc39e6f6a2144f8a9a168b242f58 (remote response: 429: Too Many Requests)'

**Comment by binman-docker** [comment]
That is indeed our overall "anti-abuse" rate limit, documented here: https://docs.docker.com/docker-hub/download-rate-limit/#other-limits

Generally when we see this happen, it's because of some sort of automation that's gone a bit crazy. I would check your infrastructure for any cron jobs or healthchecks against Hub that are too frequent, or a system that is failing and pulling an image over and over - things like that. You may also encounter this if you share an IP with a lot of other users - in this case we often recommend running a mirror: https://docs.docker.com/registry/recipes/mirror/

**Comment by nittools** [comment]
Hi

Any chances for our IPs to get onto slightly more permissive list? We're quite a big company in Poland (mbank.pl) and even though we're using artifactory as a proxy between our CICD servers and hub.docker we're still getting http429 errors.

I'll try to configure artifactory to be getting to the hub.docker less frequently, but it still may not be enough.

Regards

**Comment by binman-docker** [comment]
We've been considering raising the overall limit but no timeline currently. 

Would love to get feedback on that though - do you have a feel for how many requests per minute you might actually need? What percent of your requests fails? Thanks!

**Comment by nittools** [comment]
On friday 30th of october there were 49880 requests sent to hub.docker from my IPs. Need to find a way how to count those failed ones.
