### ISSUE TITLE
Docker buildhooks failing on dockerhub autobuilds if buildcontext is not pointing to the directory where the Dockerfile lives

### ISSUE THREAD

**Issue by dragonchaser** [docker/hub-feedback#2042]
## Problem description
I have a repo that contains a `/docker` folder where multiple `Dockerfiles` live. 
When I create an autobuild that sets the build context to `/docker` the build is working fine and the hooks are being invoked.
When I set the build context to `/` and point to `/docker/Dockerfile` the hooks are not being executed.
I have tried to symlink `/docker/hooks` to `/hooks` in the repository, but this is not working either.

The documentation https://docs.docker.com/docker-hub/builds/advanced/#custom-build-phase-hooks states that the hooks folder must be placed on the same level as the `Dockerfile`. 
```
Create a folder called hooks in your source code repository at the same directory level as your Dockerfile. 
Place files that define the hooks in that folder. Hook files can include both docker commands, and bash 
commands as long as they are prefixed appropriately with #!/bin/bash. 
The builder executes the commands in the files before and after each step.
```

**Comment by Glotzon** [comment]
+1

**Comment by jnovack** [comment]
It seems the current working directory becomes the path the `Dockerfile` is, that's great and all, but that's NOT what I was expecting, especially considering you told me that the *Dockerfile Location* is relative to the *Build Context*.  If the *Build Context* is relative to the root of the repository, why isn't the current working directory the root (of the repository)??

This means, you can't have a generic `build` hook calling `docker build -t $IMAGE_NAME .` because the *Build Context* is never passed to `build` so you have FIGURE OUT where you are in relative to the root of the repository if you want to build from the root (or edit your `build` hook PER `Dockerfile` if you put them in different locations).

Why does `build` get the variable `$DOCKERFILE_PATH` (presumably to use it for `-f $DOCKERFILE_PATH`) when you are already in the directory?  Why doesn't `build` get `$REPOSITORY_PATH` so that we can BUILD the root without having to figure out where we are and go there?  It's just inconsistent. 

### My Build Rules:
 * Dockerfile Location: `build/package/Dockerfile`
 * Build Context: `/`

### My (truncated) Structure:
```
# ls -l
README.md
build/package/Dockerfile
build/package/hooks/build
```

### Build Log
```
Cloning into '.'...
Warning: Permanently added the RSA host key for IP address '140.82.112.4' to the list of known hosts.
Reset branch 'master'
Your branch is up-to-date with 'origin/master'.
Executing post_checkout hook...
[***] Not a shallow repository.
[---] Unknown target architecture, skipping qemu-user-static download
Executing build hook...
[***] Build hook starting...
[---] CURRENT WORKING DIRECTORY: /src/b8mrnuudauyvneix7vgynpf/build/package
[---] DOCKERFILE_PATH: build/package/Dockerfile
[---] DOCKER_REPO: index.docker.io/jnovack/whoami
[---] IMAGE_NAME: index.docker.io/jnovack/whoami:latest
[---] APPLICATION: whoami
[---] GITHUB_USERREPO: jnovack/whoami
[---] DESCRIPTION: Sample Webserver Docker Container for Endpoint Testing
[---] BUILD_PATH: ../../.
+ docker build --file build/package/Dockerfile --build-arg APPLICATION=whoami --build-arg BUILD_RFC3339=2020-11-21T14:59:54Z --build-arg REVISION=1be0c06 --build-arg PACKAGE=jnovack/whoami --build-arg 'DESCRIPTION=Sample Webserver Docker Container for Endpoint Testing' --build-arg VERSION=v1.4.0-7-g1be0c06 -t index.docker.io/jnovack/whoami:latest_amd64 ../../.
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /src/b8mrnuudauyvneix7vgynpf/build/package/build: no such file or directory
+ docker push index.docker.io/jnovack/whoami:latest_amd64
The push refers to repository [docker.io/jnovack/whoami]
An image does not exist locally with the tag: jnovack/whoami
+ docker tag index.docker.io/jnovack/whoami:latest_amd64 index.docker.io/jnovack/whoami:latest
Error response from daemon: No such image: jnovack/whoami:latest_amd64
[***] ...build hook complete.
Pushing index.docker.io/jnovack/whoami:latest...
Push failed. Attempt 2 in 60 seconds.
Push failed. Attempt 3 in 60 seconds.
Push failed. Attempt 4 in 60 seconds.
Push failed. Attempt 5 in 60 seconds.
{u'message': u'An image does not exist locally with the tag: jnovack/whoami'}
```

I could've saved you a hell of a lot of processing time if it was consistent and documented.

-----

To get it working your `build` hook should do the following (as you see fit):

```
# Extract the root of the repository from the $DOCKERFILE_PATH variable
# e.g. "Dockerfile" becomes ""
# e.g. "build/package/Dockerfile" becomes "../../"
BUILD_PATH=$(echo ${DOCKERFILE_PATH}| sed 's#/#..#g' | sed 's#[a-zA-Z0-9]\+#/#g' | cut -c 2- )

# Build, adding an EXTRA DOT at the end of the $BUILD_PATH (for safety)
# e.g. "" becomes "."
# e.g. "../../" becomes "../../."
docker build \
    --file $(basename ${DOCKERFILE_PATH}) \
    -t ${IMAGE_NAME} \
    ${BUILD_PATH}.
```

**Comment by burnsjeremy** [comment]
This is still an issue and I had to do the same. I am building two images with automated builds and need to call one with the current tag from the other one. So I needed to setup the hooks/build also and quickly found out that it was not going to be easy. I had been searching for an hour after trying for an hour trying different options for that. I have my Dockerfiles inside of the service folder that it is creating an image for and I really did not want to change that. I get why it is an issue and I don't and the docs for most all of this are awful. You can try to do some debugging statements like `RUN pwd` but with this error I don't even think that it gets that far. I'm not sure why we cannot get a $DOCKER_CONTEXT variable to use also. 

I know this an older issue but just wanted to say thanks for the solution and to let people know when they come here that it is an issue.
