### ISSUE TITLE
RateLimit check occasionally returns nothing instead of a number

### ISSUE THREAD

**Issue by mdegel** [docker/hub-feedback#2081]
We're currently using a check for our monitoring system to verify how many pulls are still available in order know when we run out of them. The check is implemented according to https://docs.docker.com/docker-hub/download-rate-limit/

Occasionally we started to get invalid responses, with headers looking like this:
```
RateLimit-Limit: ;w=21600
RateLimit-Remaining: ;w=21600
```
instead of sth. like this:
```
RateLimit-Limit: 100;w=21600
RateLimit-Remaining: 76;w=21600
```

The request itself hasn't changed and works most of the time as intended.

Further information:
- We saw the behaviour first at 2021-02-27 12:40:10 (GMT+1)
- We saw the behaviour last at 2021-03-19 06:11:12 (GMT+1)
- We are running the checks each hour in order not to waste pull requests
- The behaviour is reproducible from other systems in the network and seems to be active for at least multiple minutes

**Comment by rauschbit** [comment]
We have the same problem - I posted it on Twitter mentioning the Docker team - hopefully someone answers...

- We saw the behaviour 2 weeks ago (~around 8. of march) for the first time
- We saw the behaviour last at 2021-03-22 15:04 (GMT+1)
- We run this check every 6 hours
- It's also reproducible from our side

**Comment by dnsmichi** [comment]
This happens occasionally since the rate limits were applied in November 2020.

I've experienced that while writing a Prometheus exporter for monitoring.
https://gitlab.com/gitlab-de/docker-hub-limit-exporter/-/issues/4

My guess is that the load balancer or proxies intercept the response header values, and sometimes there's a race condition fetching null values.

**Comment by dnsmichi** [comment]
@mdegel You can use HEAD requests which do not decrease your remaining pull counts.

https://gitlab.com/gitlab-de/check-docker-hub-limit/-/merge_requests/2

**Comment by mdegel** [comment]
@dnsmichi Thanks for the info, I wasn't aware of that. That's good to know.

**Comment by nebuk89** [comment]
@dnsmichi is this still happening for you? 👀

**Comment by rauschbit** [comment]
@nebuk89 I think the headers changed on 13. may from
```
RateLimit-Limit: 100;w=21600
RateLimit-Remaining: 76;w=21600
```
to
```
ratelimit-limit: 100;w=21600
ratelimit-remaining: 76;w=21600
```
so they are lower case now, am I right?

And to answer your question from my side - I had no such problems since 02. April as I can see on my monitoring...

**Comment by sudo-bmitch** [comment]
@rauschbit 

> so they are lower case now, am I right?

Those fields are case insensitive.

Ref: https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html

> Each header field consists of a name followed by a colon (":") and the field value. Field names are case-insensitive.

**Comment by rauschbit** [comment]
@sudo-bmitch
many thx for the fast answer!
interesting - until the 13th of may my script checked against these fields with a case-sensitive check and worked without any problem.
from that date on the field's where lower-case and i had to change my script so that it works again...
i was wondering by myself that they were upper case last year during i implemented it but it worked.
here is my gist from back than -> https://gist.github.com/rauschbit/bb3a1947cb621c52da3eaa6473b2c688 
i'll change it in the next days so that it works again.

**Comment by sudo-bmitch** [comment]
@rauschbit I've written a similar parser in [regclient](https://github.com/regclient/regclient) that outputs the results in json (by default, you are also able to format with Go templates), that you may find useful for automations:

```shell
$ regctl image ratelimit ratelimitpreview/test:latest
{
  "Remain": 200,
  "Limit": 200,
  "Reset": 0,
  "Set": true,
  "Policies": [
    "200;w=21600"
  ]
}
```

The main reason I went through the trouble to write various Go apps for this is to avoid the need to make custom auth handling for every registry.
