### ISSUE TITLE
Rate limits are very restrictive for manifest pulls.

### ISSUE THREAD

**Issue by starcraft66** [docker/hub-feedback#2093]
## Problem description
For quite some time now, docker hub has enforced image pull rate limits. In terms of image blob pulls, the pull limit seems quite reasonable as blob pulls use a lot of bandwidth. However, it appears that manifest pulls (which barely use any bandwidth at all) are also included in the pull rate limit which makes this limit unreasonably restrictive for docker image update software such as `https://github.com/argoproj-labs/argocd-image-updater`. Checking for an image tag's updated digest quickly runs you into the rate limit depending on the frequency of checks and the the amount of images to check.

Are there any plans to make manifest and blob pulls separate rate limits and raise the limit for manifest pulls?

**Comment by binman-docker** [comment]
We have some discussion of why the limits are the way they are here:

https://www.docker.com/pricing/resource-consumption-updates
https://www.docker.com/blog/scaling-docker-to-serve-millions-more-developers-network-egress/

The TL;DR version is that while limiting blobs might make more sense technically (and we did that at first), they are a lot harder for users to estimate and they don't correlate linearly and predictably with "pulls", which is how most people interact with a registry. Manifest requests have a direct and predictable 1 to 1 (or 2 to 1 for multi-arch images) relation to pulls.

**The good news** is that there is a way to handle what you're trying to do - use HEAD requests rather than GET and compare the Docker-Content-Digest header. Several tools have already adopted this, such as Watchtower: https://github.com/containrrr/watchtower/pull/674

We would also encourage setting reasonable defaults for check intervals.

**Comment by starcraft66** [comment]
Thank you, I will suggest adopting `HEAD` requests for this kind of checking to the ArgoCD developers!

**Comment by tboby** [comment]
@binman-docker  `HEAD` is a good solution if you only need the digest, but what if you need the annotations?

The docker official images don't include OCI pre-defined annotation keys inside the image labels, but they are in the manifest annotations. This provides a way for security scanners/patching tools to get the version of the application in an official image from the digest.

As far as I can tell, this is currently the only way to trace back to application version from a running container based off an official docker image. https://github.com/docker-library/cassandra/issues/260#issuecomment-1371436416 indicates this is by design. I don't believe the docker engine API exposes (or even uses) the annotations from OCI manifests.

This data shouldn't change, so caching helps, but if the user has more than a handful of official images running it becomes very difficult to work out what the user is running and then also have the quota to update in a single interactive session.
