### ISSUE TITLE
Adding github repo to dockerhub when creating a repository - organisation list is empty

### ISSUE THREAD

**Issue by magick93** [docker/hub-feedback#2116]
I'm trying to create a repository in Dockerhub, to enable automatic Dockerfile builds.

I have connected my Github account to Dockerhub.

![image](https://user-images.githubusercontent.com/2173213/123595619-a670f980-d7e0-11eb-9944-7f237061f11d.png)

In the browser console I see the following:

```
{
"response": null, 
"error": 
"Error trying to get GitHub user: 401 Client Error: Unauthorized for url: https://api.github.com/user"
}
```

Is this something I can fix, or is it a bug on the Dockerhub side?

**Comment by mikeparker** [comment]
Can you give more details? What's the problem? What are you unable to do?

Also, are you on a free plan or a paid plan, and are you a user or an organisation?

**Comment by magick93** [comment]
I'm not seeing any of my github organizations (that are authorized to use dockerhub) in the `Select organization` field. 

I'm on the free plan. And I'm a user who is admin of 2 orgs.

**Comment by mikeparker** [comment]
Due to excessive crypto-mining abuse, unfortunately we are in the process of deprecating Autobuilds for free users, please see blog post here for details https://www.docker.com/blog/changes-to-docker-hub-autobuilds/

What you're seeing is likely parts of our system shutting down as part of this. Sorry this is a bad experience, the crypto-miners forced us into a bad position here. :(

**Comment by magick93** [comment]
Ok, sorry to hear that.

Thanks for clarifying/
