### ISSUE TITLE
Windows images vulnerability scanning

### ISSUE THREAD

**Issue by gillg** [docker/hub-feedback#2151]
## Problem description

Hello, I enabled the vulnerabilities scanning on one of my repo which contains windows images some days ago.
For now I don't have any trace of success or failed scans. This feature seems just not work silently with windows images.
Anyone can confirm ? If it's the case you really should remove the "scan" button on a repo where we have windows images, or at least add a status "not supported" in the scan result column. Today we are completly blind on what happen.

**Comment by mikeparker** [comment]
https://docs.docker.com/docker-hub/vulnerability-scanning/

> Docker Hub currently supports scanning images which are of AMD64 architecture, Linux OS, and are less than 10 GB in size.

We can't remove the scan button on a repo with windows images because people often have windows and linux images together, and it would require checking the architecture of every image, and also if they then start pushing linux images this way the scan will start working.

However, I appreciate that it'd be nice to have a scan status indicator to give an appropriate error message or warning on unscannable images.
