### ISSUE TITLE
Add slirp4netns installation to Distribution-specific hint

### ISSUE THREAD

**Issue by keelung-yang** [docker/hub-feedback#2213]
Hi,
No installation of `slirp4netns` metioned in official document [Run the Docker daemon as a non-root user.](https://docs.docker.com/engine/security/rootless/)

The `slirp4netns` is only available in [Ubuntu ≥ 20.04](https://packages.ubuntu.com/search?keywords=slirp4netns&searchon=names&suite=all&section=all).
So saying `Known to work on Ubuntu 18.04, 20.04, and 21.04` is not true without installing `slirp4netns`.

So please document installation of `slirp4netns`.
Or users should get error if using Ubuntu 18.04
```
Mar 01 14:47:15 xps dockerd-rootless.sh[2570]: Either slirp4netns (>= v0.4.0) or vpnkit needs to be installed
Mar 01 14:47:15 xps dockerd-rootless.sh[2570]: + exit 1
```

**Comment by binman-docker** [comment]
Hi @keelung-yang - thanks for reporting the issue. This isn't related to Docker Hub, so I'm going to close this issue here.

It looks like the docs do mention installing slirp4netns on Debian, but not Ubuntu. You could open a PR to change that here I think: https://github.com/docker/docker.github.io/blob/5bcc3246889f374e1aaaa3b4ff90d6f0e6e7a314/engine/security/rootless.md?plain=1
