### ISSUE TITLE
IP Range for production.cloudflare.docker.com 

### ISSUE THREAD

**Issue by pranaysharmamanulife** [docker/hub-feedback#2218]
Looking for an IP Range to enter in the firewall to unblock docker pulls. Currently the firewall is failing connection for production.cloudflare.docker.com

**Comment by ingshtrom** [comment]
Docker Hub Registry uses Cloudflare as the CDN for serving Docker Image layer blobs, manifests, etc. This means that in order to allow access to Docker Hub through a firewall, you would need to allow-list all of the [Cloudflare IPs](https://www.cloudflare.com/ips/). Of course, then you will allow traffic from any Cloudflare-based site, which can be a concern.
