### ISSUE TITLE
Number of docker pull is not increasing

### ISSUE THREAD

**Issue by mortymacs** [docker/hub-feedback#2222]
## Problem description

Recently, we realized that the number of "docker pull" is not increasing while we have many docker pull every day.

## Debug Information

**URL**: https://hub.docker.com/r/atkrad/wait4x

# Task List
- [x] This is **NOT** a security issue
- [x] I do **NOT** have a Docker subscription
- [x] I have looked through other issues and they do **NOT** apply to me

**Comment by ingshtrom** [comment]
How are checking the number of pulls of your image? When I go to [hub.docker.com/r/atkrad/wait4x](https://hub.docker.com/r/atkrad/wait4x) I see that there are `500k+` pulls. I wouldn't expect that number to increase until it hit the next milestone, I believe that is `1B+`.

<img width="1323" alt="image" src="https://user-images.githubusercontent.com/571756/160642384-51243b53-3900-49ee-941f-89dfb05b7553.png">


Do you have screenshots of what number(s) you are looking at so that we can ensure we are comparing apples with apples?

As a test, I did just do a pull and waited a minute before pulling up the page again. The API response properly showed the increase in pulls by 1. 

NOTE: the pull counter is not immediately updated in the UI, so you may need to wait a minute or two in order for the number to reconcile.

**Comment by mortymacs** [comment]
Hi,
Thanks, @ingshtrom :+1: 
Recently, we did some checks and realized that it works fine. So, no need for any action.
So, I'm going to close the issue.
Thanks.
