### ISSUE TITLE
Cannot delete old tags

### ISSUE THREAD

**Issue by dimaqq** [docker/hub-feedback#2265]
I've inherited a public repo under our org.
I've made the repo private.
There are 2 image tags ~1 year old.
When I try to delete one or both of these old tags, I get this error:

POST to https://hub.docker.com/v2/namespaces/rrdockerhub/delete-images with request data:

```js
{"dry_run":true,"manifests":[{"repository":"postgis","digest":"sha256:803d7a89cf8959ec4b2d999010546b4af93825a9ed268669c36a7bf601152088"},{"repository":"postgis","digest":"sha256:b1ab95fa6ae7b0eab2d007795b7bb6f92e9872c8852e4e8b93e3927a4840c691"}]}
```

400 Bad Request with response data:
```js
{"message":"httperror 400: validation error"}
```

This happen on clicking the trash bin. before I even have a chance to confirm deleting the tags.

**Comment by milosgajdos** [comment]
Hi, @dimaqq thanks for opening the issue. I had a quick look into this -- I can see someone is trying to create `rrdockerhub/postgis` repository despite its already existing and failing with `400`.

This seems however unrelated to the issue reported by you which is rather peculiar because I can't seem to be able to find anything in our logs.

**Comment by milosgajdos** [comment]
@dimaqq can you please check if you are still experiencing this issue?

**Comment by dimaqq** [comment]
Indeed creation attempt was unrelated.

Someone (another admin probably) managed to delete these very old tags in the meantime, I no longer have the preconditions to attempt to reproduce.
