### ISSUE TITLE
Please remove IP from blacklist

### ISSUE THREAD

**Issue by FrancescoMez79** [docker/hub-feedback#2272]
Hello,
from some days hub.docker.com is issuing error:
"message": "You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit"

Investigating we have understand that our public IP : 84.253.147.38 has been blacklisted.
We are re-checking our watchtower configuration. 
We have removed the "interval" field (that was 30seconds)  which by default should now be 24 hours.

May you please remove our IP from docker blacklist?

Thanks and best regards,
Francesco

**Comment by ingshtrom** [comment]
It seems you are continuing hit rate limits due to watchtower configuration changes since you posted about something similar last week https://github.com/docker/hub-feedback/issues/2268. 

I'm not sure what watchtower version you are using, but please ensure that it is up to date. In the past couple of years, they have made some improvements that limit the interval for scanning Docker Hub and use HEAD requests instead of GET requests. HEAD requests do not count against the rate limit 😄 

As [commented in response to your previous ticket](https://github.com/docker/hub-feedback/issues/2268#issuecomment-1239525978), rate limits work on a rolling 6-hour interval. As you reduce your pulling of Docker Hub images and time goes on, you will automatically have your IP or user removed from the rate limit.

Do note that if you [add your Docker Hub credentials (username and personal access token) in watchtower](https://containrrr.dev/watchtower/private-registries/), your rate limit amount will be increased. This is shown on our [pricing page](https://www.docker.com/pricing/) under the header "Image Pull Rate".
