### ISSUE TITLE
False positive for Log4j in library/elasticsearch:8.5.0

### ISSUE THREAD

**Issue by jkakavas** [docker/hub-feedback#2281]
Hi there folks, 

library/elasticsearch:8.5.0 is erroneously reported as having a critical vulnerability related to Log4j. 
![Screenshot 2022-11-03 at 4 45 18 PM](https://user-images.githubusercontent.com/10281256/199752744-66a7e957-af64-42e3-a8d7-ddaa5fa577a7.png)

I would assume you run docker scan on the background but this doesn't seem to be the case. You can verify that the docker image doesn't include any critical vulnerability related to log4j, by running any of the following:

Docker Scan ( using Snyk )
```
docker scan docker.io/library/elasticsearch:8.5.0 --severity high
```

or trivy

```
trivy image docker.io/library/elasticsearch:8.5.0 --security-checks vuln
```

Can you please rectify this as the warning is misleading for users?

**Comment by eunomie** [comment]
Hi,
Thank you for the report.

There was indeed a bug in the detection of the vulnerability.

It has been fixed and `elasticsearch:8.5.0` is now green as expected.

<img width="791" alt="image" src="https://user-images.githubusercontent.com/1542321/199936949-76efa591-6b29-4dbd-b18c-e4651d3d20c4.png">

**Comment by jkakavas** [comment]
Thank you @eunomie ! Could you please share some information around what tooling you are using to provide these checks and warnings ? We will be very interested in doing the due diligence ourselves before the releases are made public on docker hub so that we are not affected by any tooling related false positives in the future 🙏 Is it `docker scan` with Snyk in the background ?

**Comment by eunomie** [comment]
The Hub feature about vulnerabilities is not using `docker scan` but both of them are using `snyk`.
The detail here is we also have some custom code that checks specifically `log4j` jars.
Roughly the issue here is from the initial CVE the `2.12.z` versions were marked as vulnerable. Thing that changed later.

I'll see if I can simply relax those jar verifications (that was made at the time other tools were not ready for that) and only rely on Snyk. That way you can check it locally using `docker scan` before push.

I'll keep you posted about it.
