### ISSUE TITLE
Issue in installing NodeJS in docker container

### ISSUE THREAD

**Issue by Rajithang** [docker/hub-feedback#2299]
We want to deploy containers via Azure DevOps CI/CD pipeline and you are using the URL - [https://deb.nodesource.com/setup_18.x] to install nodeJs in the docker container during container build process.

On Devops server, docker script tries to connect  [http://deb.debian.org] site that is having http protocol for which we don’t have any control. We would like to allow access this URL from our Devops Linux agent server. Due to firewall restrictions, http url is blocked. 

Please suggest if there is an alternate way to install nodeJS or bypass http url.

Thanks in advance

**Comment by ingshtrom** [comment]
Hello @Rajithang 👋 

Thank you for reporting this, but I am having trouble understanding how this is related to the services Docker provides. This GitHub repository is focused on issues relating to service that Docker provides, mainly the software as a service that we provide. At first glance, this sounds like a question that would be better answered in [our forums](https://forums.docker.com/) or the [Docker StackOverflow community](https://stackoverflow.com/questions/tagged/docker?tab=Newest), but let's see if I can help you further.

Can you please provide clarity on the following items so I can help you better?

> We want to deploy containers via Azure DevOps CI/CD pipeline and you are using the URL - [https://deb.nodesource.com/setup_18.x] to install nodeJs in the docker container during container build process.

When you say, "...you are using the URL..." what do you mean? Are you following a guide from us or is this set in your Dockerfile?


> On Devops server, docker script tries to connect [http://deb.debian.org] site

What is the "docker script" that you are referring to? What commands are you running in order to reproduce this?

**Comment by Rajithang** [comment]
Hello @ingshtrom Thanks for your response. Let me explain it in detail. 

We’ve created a new ASP.Net core + Angular application. We are deploying the application in AKS Container via Azure CI/CD process. We’ve added the below commands in the docker file (Container) to install Node in the container during runtime. I've attached the docker file too.

![docker file](https://user-images.githubusercontent.com/120545928/207665402-77c7f5ee-7dbd-4f55-bf51-8a46c2132a39.png)

_**#Install NodeJs
RUN apt-get update && \
apt-get install -y wget && \
apt-get install -y gnupg2 && \
wget -qO- https://deb.nodesource.com/setup_18.x | bash - && \
apt-get install -y build-essential nodejs
#End Install**_

We’re using the URL - https://deb.nodesource.com/setup_18.x to install nodeJs in the docker container during container build process. On Devops server, this script gets executed internally & tries to connect to http://deb.debian.org/ site. 

In my organization, firewall restrictions are in place to prevent any http call from Devops server. This is preventing the script from getting executed.

Below is the log from DevOps

+ apt-get update
Err:1 http://deb.debian.org/debian bullseye InRelease
  Could not connect to deb.debian.org:80 (199.232.106.132), connection timed out
Err:2 http://deb.debian.org/debian-security bullseye-security InRelease
  Unable to connect to deb.debian.org:80:
Err:3 http://deb.debian.org/debian bullseye-updates InRelease
  Unable to connect to deb.debian.org:80:
Reading package lists...
W: Failed to fetch http://deb.debian.org/debian/dists/bullseye/InRelease  Could not connect to deb.debian.org:80 (199.232.106.132), connection timed out
W: Failed to fetch http://deb.debian.org/debian-security/dists/bullseye-security/InRelease  Unable to connect to deb.debian.org:80:
W: Failed to fetch http://deb.debian.org/debian/dists/bullseye-updates/InRelease  Unable to connect to deb.debian.org:80:
W: Some index files failed to download. They have been ignored, or old ones used instead.

Our security team is not allowing to open port 80 for accessing the http url as this will lead to security risk. 

Do we need to make any changes in the docker file or any settings? We would like to know if we're following the correct steps and also if there is any workaround to overcome this http call. 

Hope I've responded to all your queries. Please advise if I need to post this question in any other forum that can help me out.

Thanks!!

**Comment by ingshtrom** [comment]
Ah, gotchya. I _think_ this could be happening with the various `apt-get` commands you are running and the default values for your [`sources.list` file](https://linux.die.net/man/5/sources.list). I would look at those files and see if you can modify them to be `https` instead of `http` 😄 

In the future, I recommend this question be asked in a different place, like the forums or StackOverflow, as I mentioned above.

**Comment by thaJeztah** [comment]
debian package repositories always defaulted to non-TLS (http); I think their reasoning was that packages would be verified through signing, so TLS was not needed to verify the packages (and would only add additional overhead). I _think_ this changed a bit over time, and it's possible to use TLS connections now (or otherwise you can configure a mirror to be used). You'll likely be able to find more information about this if you search, but a quick search gave me this discussion on StackExchange (which contains some tips and useful links); https://unix.stackexchange.com/questions/90227/why-is-there-no-https-transport-for-debian-apt-tool
