### ISSUE TITLE
Extremely slow image pulls in Singapore region

### ISSUE THREAD

**Issue by jenademoodley** [docker/hub-feedback#2390]
## Problem description

- When pulling an image from a VM in southeast asia (specifically SIngapore) the image pull takes an extremely long time.
- It is worth noting that not all images are effected (the nginx image downloads as expected), and also not all layers. For example, the `grafana/oncall:v1.3.115` image has issues with layers 7, 10, and 12:
- This issue is observed in AWS EC2 instances, as well as Google Cloud VMs. As such issue is not isolated to any cloud-provider and appears to be on DockerHub's side
- The issue is only observed in Singapore. Testing in Dublin on AWS (eu-west-1 region) the image pull works as expected

# Task List
- [X] This is **NOT** a security issue
- [X] I do **NOT** have a Docker subscription
- [X] I have looked through other issues and they do **NOT** apply to me

**Comment by sjainaajtak** [comment]
We are also observing same issue on our EC2 server in Singapore region. The issue if for our private dockerhub repositories but public repositories are working fine. We have checked from Mumbai (ap-south-1) and the image pull works there.

**Comment by guillemsf** [comment]
It happens to me, I wrote to dockerhub support a few hours ago. It works to me in us-east-1 and in eu-west-1

**Comment by binman-docker** [comment]
Hi folks, we're looking into this. If you open a [support ticket](https://hub.docker.com/support/contact), we can (securely) collect some information that will help us troubleshoot the issue with our CDN provider. Thanks!

**Comment by guillemsf** [comment]
Hi, I opened it 9 hours ago :/

this is the thread thread::UL33nXfrEZOcIDe5SD0qHAQ::

**Comment by abirdatta** [comment]
We are also facing exact same issue of from AWS Fargate service in both Singapore and Jakarta region. Also the issue is intermittent, and affecting specific layers of an image, in our case for private org/repo images.
We also raised a support ticket yesterday **thread::mfp2QWSzGzeaAA0rpbUiLQQ::**

**Comment by jenademoodley** [comment]
Created a support case as well should any further information be required.

Testing again today and I can see there has been some improvement. Previously image `grafana/oncall:v1.3.115` had an issue with layer 7 but that layer was able to be pulled from Singapore without any issues. Other layers are still facing issues though (layers 12 and 13).

**Comment by kweefc** [comment]
i have same issue under Malaysia East. pulling very slow speed around 30-50kb/s only even i got 300mbps line.
![Uploading Screenshot 2024-06-15 163619.png…]()

pull 26mb for 30min

**Comment by NavindrenBaskaran** [comment]
i'm experience slow docker image pull from our AWS `ap-southeast-1` region and Malaysia as well.

**Comment by angyts** [comment]
Oh my, yes, same for us. its driving us crazy.

**Comment by claytonchew** [comment]
👍 Thanks @jenademoodley for encountering this issue and raising this.

The slow down is becoming a major issue across our clusters located in `ap-southeast-1`, we had to pulled back our scheduled major deployments in these area.

**Comment by gabrielsim** [comment]
Also experiencing the same issue when pulling from a residential ISP in Singapore (M1). Some layers are quick to download whilst the others are barely moving at all.

**Comment by nsheaps** [comment]
We did some traceroute-ing from an eks cluster in ap-southeast-1 after experiencing failed image pulls for over an hour on some images. We've seen a variety of symptoms including:
* EOF during pulls
* Authentication errors to our private repositories before pulls
* Affecting both public and private repositories
* Slow download speeds at about 1MB/s
* as mentioned before, some images pulls were fine
* affected all of our AZs in the ap-southeast-1 aws region (Singapore)
* packet loss

During the traceroute, we noted that ap-southeast-1 calls to docker.io (not necessarily the registry URL), were getting routed to aws us-east-1 (based on public IP). Is there a location closer that it _should_ have been routed to?

After discussing with AWS, their suggestion was to use something like ECR or hosting the image registry ourselves. Until we have this set up, we've effectively cut off the ap-southeast-1 region from our deploys and customer interactions, since we currently have a deployment mechanism that waits for deployments in k8s to become ready before proceeding (and times out after 1hr, even if it's just rolling 3 pods). We are also going to start testing docker's `registry` image as a pull through cache, and host in us-east-1. So far image pulls have been successful, even though in theory it's similar network pathing. ap-southeast-3 was our fallback plan due to it's close proximity to ap-southeast-1 but it sounds like that might not be feasible based on @abirdatta 's testing in Jakarta.

**Comment by gabrielsim** [comment]
Issue has recovered for me

> Also experiencing the same issue when pulling from a residential ISP in Singapore (M1). Some layers are quick to download whilst the others are barely moving at all.

Issue has recovered for me, pulls are quick to download again

**Comment by guillemsf** [comment]
Not in ap-southeast-1, this is really painful and it's even worse to not have any answer after 4 days from docker support team.

**Comment by abirdatta** [comment]
pulls are still very slow for us in Singapore(ap-southeast-1) and Jakarta(ap-southeast-3) region. downloads of some specific layers are taking long time. things were better yesterday and over weekend.

**Comment by RaveSplash** [comment]
Are there any workaround for this, for example changing the ec2 instance to another region?

**Comment by rolandjitsu** [comment]
Same issue here. It happens locally in our office and on all GCP/AWS machines located in asia-southeast (Singapore). Any image we pull from docker.io takes hours now.

We got around it by using GCP's artifact registry for some of the images that we customised.

**Comment by brianchen003** [comment]
Same issue here. It happens locally in our office and on all GCP/AWS machines located in asia-southeast-b (Singapore). Any image we pull from docker.io takes hours now.

We got around it by using GCP's artifact registry for some of the images that we customised.

**Comment by noginahalchetan** [comment]
Facing same issue on all my EKS clusters running in Singapore region since Friday. The problem is specific to Docker registry. For quay.io it works fine.

**Comment by narthanaj** [comment]
facing same issue :/

**Comment by ChypherAtWork** [comment]
Yes, I am facing the same issue. Does anyone have answer please share it I am stuck in between.

**Comment by rolandjitsu** [comment]
We should probably avoid spamming and just +1 the issue to show how many of us are facing the issue.

**Comment by Yaga07** [comment]
+1

**Comment by Keval-kanpariya** [comment]
Same issue here +1

**Comment by ManavKakani** [comment]
+1

**Comment by Pradipkhuman** [comment]
same issue +1

**Comment by ahmadfadlydziljalal** [comment]
Same issue here +1

It takes forever for just pull my public repo in docker hub.

```
dzil@potts:~/app$ ping hub.docker.com
PING prodextdefgreen-k0uuibjyui-4ec6503f7037d339.elb.us-east-1.amazonaws.com (44.193.181.103) 56(84) bytes of data.
```

**Comment by pacharapold** [comment]
+1

**Comment by liuyehcf** [comment]
+1

**Comment by 1902sysad** [comment]
same issue +1

**Comment by kaikiat** [comment]
+1

**Comment by tanyudii** [comment]
+1

**Comment by zoechou** [comment]
+1

**Comment by RaveSplash** [comment]
It's getting better guys !!!

**Comment by jenademoodley** [comment]
Haven't experienced the issue in some time. Happy to close this now.

**Comment by libterty** [comment]
+1， it's still slow in ap-southeast-1

**Comment by armona** [comment]
We are still experiencing the same issue with DockerHub.

**Comment by oliviermtl** [comment]
Having the same issue on ap-southeast-1 using docker pull from a private ECR

**Comment by ceecer1** [comment]
Extremely slow docker push to ap-southeast-1, experiencing since March 2025. Any ideas??

Pushing docker image
The push refers to repository [XXXXXXXXXX.dkr.ecr.ap-southeast-1.amazonaws.com/$$$-repository/blah-blah]
b5bcc142d1d5: Pushed 
74d34539a763: Pushing [==================================================>]  606.1MB
56a4e22ea67c: Pushing [==================================================>]  606.1MB
cc4e4566e1df: Pushed 
4a6269920af2: Pushed 
bfea7dc378a6: Layer already exists 
0b89a4bd16ab: Layer already exists 
a174a15738a0: Layer already exists 
0fa41641ddb7: Layer already exists 
eceeef274cdc: Layer already exists 
29a446e7b1ba: Layer already exists 
f8d8ca814643: Layer already exists 
83b767b06655: Layer already exists 
14fbd8039ba4: Layer already exists 
da55b45d310b: Layer already exists

**Comment by tarkilhk** [comment]
Facing this same issue in Feb 2026
