### ISSUE TITLE
adding a build when you have multiple git repo accounts.

### ISSUE THREAD

**Issue by sparklyballs** [docker/hub-feedback#278]
i am a member of an organisation with git as well as having my own personal repo, when i attempt to add a container from the organisation repo the name field reverts to my personal repo and it has to be changed to the orginisation repo before the build can progress.

When that's done, and with the build set to be automatically triggered i still have to trigger the first build, not like it used to be and not my definition of "automatic"

**Comment by rrarunan** [comment]
@sparklyballs Can you confirm what `namespace` you see in the URL query parameters when this happens?

**Comment by sparklyballs** [comment]
@rrarunan i video'd it as i'm not the most descriptive of people.
https://www.youtube.com/watch?v=5DAAt8uNC8w&

**Comment by rrarunan** [comment]
ok, I see. If you see in the video, the `namespace query ` points to `linuxserver` which is the `docker org namespace` that is default, since you probably were on your organization dashboard when you started the automated build creation process. The list that you saw was the `github organization` and `github repositories` that you want to set up your automated build on. Since, both the docker hub and github orgs are probably the same name its confusing for you to see `linuxserver` picked as the default namespace.

But, to make things clear: the `namespace` you see in the form, is the `docker hub org` namespace, while the list of orgs/user you see in the previous screen is the github repositories' user or org. So, I understand why this may be confusing, especially since the names are _exactly_ the same in your case. 

This seems like a very specific UX issue. We could improve this to make it a little clearer, to distinguish between the github and dockerhub repositories/user/orgs. 

Let me know if you want me to explain a little more.

**Comment by sparklyballs** [comment]
i understand your explanation, but it doesn't take away the frustration factor on what should be a relatively simple thing to sort.
i can't be the only user who has multiple repos to work with.
UX is key, it's your shop window.

**Comment by rrarunan** [comment]
Thanks @sparklyballs We will work on this to make the flow better.
