### ISSUE TITLE
README not being parsed on build

### ISSUE THREAD

**Issue by klingtnet** [docker/hub-feedback#300]
I have a README.md in every of my github repos but docker hub refuses to use them on automatic builds. Take my [prosody](https://hub.docker.com/r/klingtdotnet/prosody/) image for example, the _build details_ show that the `readme_contents` are empty but the [file](https://github.com/klingtnet/docker-prosody/blob/master/README.md) is in the same folder as the `Dockerfile`.

**UPDATE** I had made custom description which I've deleted and triggered a new build \wo success.

Maybe related to #163

**Comment by djmaze** [comment]
Same here with [an image of mine](https://hub.docker.com/r/mazzolino/phantomjs-static/).

**Comment by nathan-osman** [comment]
Same here with [one of my images](https://hub.docker.com/r/nathanosman/docker-go-cannon/) as well.

**Comment by ChristopherBiscardi** [comment]
@kencochrane Can you take a look at the APIs here? the `readme_contents` are coming back `null`.

**Comment by klingtnet** [comment]
For me the problem **seems to be fixed**, all descriptions are containing the `README.md` content. If this is the case for @nathan-osman and @djmaze, then I will close the issue.

**Comment by djmaze** [comment]
Yes, the README is present now. But now "Source Project" links to the Docker Hub page itself..?

**Comment by kencochrane** [comment]
@ChristopherBiscardi are they coming back null for everyone, or just some select projects?

**Comment by klingtnet** [comment]
@djmaze I can confirm that *Source Project* links to the Docker Hub page itself.

**Comment by kencochrane** [comment]
OK I was able to reproduce if I was not logged in and looking at my own automated build. If I'm logged in, it is working. It looks like when you are not logged in, or you are trying to look at someone else's automated build page the API for getting the automated build details is returning a 401 and since it is failing it can't get the source URL, and thus it is empty. When it is empty the browser is linking you to the same page.

@fxdgear @ChristopherBiscardi not sure if it is an API thing or a front end thing, any insight you might have, would be great.

**Comment by prologic** [comment]
Experiencing the same issue with [crux/python](https://hub.docker.com/r/crux/python/)

**Comment by ChristopherBiscardi** [comment]
@kencochrane @fxdgear Last time I checked, the API was returning `null` in the readme field for every repo mentioned. The Source Project is a separate issue, which it looks like we have to update our SDK for logged-out users.

**Comment by kencochrane** [comment]
@prologic 

I can confirm that https://hub.docker.com/r/crux/python/ is empty, digging backwards, I also confirm the API is returning null, and that is because the database has a null value. Looking at a recent build for this one.  https://hub.docker.com/r/crux/python/builds/bxsyjdueynmuargvwzbsdui/ it is looking into /python (https://github.com/cruxlinux/python/tree/master/python) for the dockerfile, that is also where it will look for the README.md file, and since it isn't there it didn't return one, and that is why the description is null.

@ChristopherBiscardi it looks like the build details also have the same problem when not logged in, it doesn't look like the JWT is passed, and gets an error when trying to access that endpoint.

**Comment by prologic** [comment]
@kencochrane Thanks for looking into this; I'll *move* the ``README.md`` again :) -- I think the hub was seeing some issues the past few days and it would "sometimes" not pick up the README.

**Comment by prologic** [comment]
@kencochrane Confirmed; that's worked finally!

**Comment by nathan-osman** [comment]
It's still not working for [this repository](https://hub.docker.com/r/nathanosman/docker-go-cannon/). New builds aren't updating the description from the `README.md`.

**Comment by dnephin** [comment]
I had this issue with https://hub.docker.com/r/dnephin/docker-zookeeper/ as well (I had to edit the description manually after the builds finished and it didn't update).

**Comment by suchja** [comment]
I have the same issue with [suchja/ea-lite](https://hub.docker.com/r/suchja/ea-lite/). I'm logged in. Is there an workaround? Really like to have this fixes.

**Comment by kencochrane** [comment]
@nathan-osman @dnephin @suchja I have confirmed that your config is correct, we are looking into what might be causing the build service from picking up the README. 

ping @dustinlacewell @caervs

**Comment by nathan-osman** [comment]
@kencochrane it seems to be working for me now.

**Comment by suchja** [comment]
@kencochrane seems to work for me as well.

**Comment by klingtnet** [comment]
Same for me, I will close this issue.

**Comment by hekaldama** [comment]
Not sure if this is the best place, but I am getting this issue right now on:

https://hub.docker.com/r/ypengineering/milieu/

Thanks for any help.

**Comment by kencochrane** [comment]
@hekaldama you config looks fine, must be a miss on our side.

pinging @dustinlacewell @caervs to see if they know why it wasn't picked up.

**Comment by hekaldama** [comment]
@kencochrane thanks.

**Comment by maport** [comment]
I think I have the same issue here:

  https://hub.docker.com/r/codesimple/elm/

My README.md is in the same (sub) directory as the Dockerfile. It builds okay but the readme doesn't come across and the build "readme_contents" is blank. I tried with and without a trailing slash on the "build_path" but that didn't make any difference.

**Comment by hekaldama** [comment]
Mine is working now but no idea why.

**Comment by kencochrane** [comment]
@maport is yours still not working?

@hekaldama we have been rolling out changes to the build system, and I wonder if you were hit with a bug, that has since been fixed.

**Comment by maport** [comment]
@kencochrane I just triggered a new build which is still in-progress. This seems to be working better since the "readme_contents" is no longer blank. But it looks like it has picked up the readme at the root of my linked repo rather than the one in the same location as the Dockerfile.

Update: The build has now completed and has used the readme at the root of my repo. Unfortunately something seemed to go wrong with the build since it has given it an "error" status and the build details are now all showing as blank.

**Comment by klingtnet** [comment]
The `README.md` is not being parsed again, see the [latest build of my docker-gogs](https://hub.docker.com/r/klingtdotnet/gogs/builds/bfjxf5ndqep6dbivgrfhefw/) image.

**Comment by Tzaphkiel** [comment]
I have the same problem for this [image](https://hub.docker.com/r/tzaphkiel/mjsmongodb/)

**Comment by carolynvs** [comment]
I have the same problem. My Dockerfile is in a subdirectory with a README.md next to it, but the build is picking up the README.md at the root and using that instead. I can't fix it manually because new builds just overwrite it.

**Comment by prologic** [comment]
Yeah this is still a problem for me too.

I notice two obvious failings here:

a) The README.md is not respected in the sub-directory where the Dockerfile
is
b) Even if the README.md is at the repoository's top-level (as well as the
Dockerfile) "sometimes" it is not read in and the description is left
blank; even after force pushes to the underlying repository.


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

On Thu, Jan 14, 2016 at 2:29 PM, Carolyn Van Slyck <notifications@github.com

**Comment by Yajo** [comment]
Also affected: https://hub.docker.com/r/yajo/pdftk-encrypt/

**Comment by waleedka** [comment]
Confirming the same problem. Started a new automated build repo, and it fetched and built the Dockerfile but ignored the README.md file.

**Comment by genome21** [comment]
Hi Waleedka,
Try putting both your dockerfile and README.me into a subdirectory.  This tends to do the trick.  For some strange reason, if there are a ton of files in the directory with the dockerfile, it skips processing the README.md file.

**Comment by genome21** [comment]
@waleedka try putting both your dockerfile and README.me into a new subdirectory. This tends to do the trick. For some strange reason, if there are a ton of files in the directory with the dockerfile, it skips processing the README.md file, and can cause issues publishing the container.

**Comment by waleedka** [comment]
@genome21 There are only 3 files in the repository. 

https://github.com/waleedka/modern-deep-learning-docker

**Comment by reypm** [comment]
Yup, this is happening to me as well, any ETA for a  fix?

**Comment by genome21** [comment]
@waleedka @reypm Try creating a new folder in your repo and placing the DOCKERFILE there.  As @prologic mentioned, "The README.md is not respected in the sub-directory where the Dockerfile
is".  This also seems to be an issue at times when the DOCKERFILE is in the root directory without any existing subdirectories.  As far as I'm aware, this issue was overlooked while emphasis was placed on the Docker Store rather than the Docker Hub.  The problem should be fixed if you become a Docker Store Publisher and port your repo there.

[https://store.docker.com/](https://store.docker.com/)

**Comment by iraklisg** [comment]
I have the same problem. 

My `Dockerfile` is in a subdirectory `/docker/app/Dockerfile` with a `README.md` next to it, and I have also a second `README.md` in the root of the repo. 

When the automated build is triggered, the mage is successfully build, the `Dockerfile` is successfully parsed but none of the two `README.md` files are picked 😕

**Comment by haximilian** [comment]
I'm experiencing the same issue on [haximilian/homemaker](https://hub.docker.com/r/haximilian/homemaker). The primary difference appears to be the fact that my README.md and Dockerfile are both in the root directory of the master branch of my repository. I believe this may have something to do with the fact that my repository was very recently experiencing autobuild issues as described in #1352.

**Comment by Tecktron** [comment]
Having this issue today as well :unamused:
