### ISSUE TITLE
Support shorter (1-3 character) usernames

### ISSUE THREAD

**Issue by ahmetalpbalkan** [docker/hub-feedback#321]
As of Docker 1.8.0, Docker supports "one character repository names". This probably can mean the same can be allowed on Docker Hub.

**Comment by md5** [comment]
I'd love to have `@md5` over there to match GitHub instead of `@mdillon`. That being said, the lack of repository redirects means that users of my existing images will likely not know if I start publishing images under the `md5` namespace. I think this is related to #11 (*Add ability to rename/delete user accounts*).

**Comment by ahmetalpbalkan** [comment]
Makes sense.

**Comment by ahmetalpbalkan** [comment]
Most probably never gonna happen.
