### ISSUE TITLE
Build Triggers sending POST with curl always trigger all tags/branchs

### ISSUE THREAD

**Issue by mfoll** [docker/hub-feedback#330]
Hi,

I have 4 builds in my repo: https://hub.docker.com/r/mfoll/robust-regression-caller. Each time I try to trigger a build by docker tag name or by source branch, it triggers the build for all the 4, and not only the one I ask in the curl command.

Thanks for your help,

Matthieu

**Comment by tkrille** [comment]
@mfoll This is because of wrong `curl` commands on the "Build Settings" page. The correct commands, depending on whether you want to trigger by branch, tag or Docker tag, would be:

**By Docker Tag**

```
$ curl -H "Content-Type: application/json" --data '{"docker_tag": "$DOCKER_TAG"}' -X POST https://registry.hub.docker.com/u/$ORGANIZATION_OR_USER/$REPO/trigger/$TRIGGER_TOKEN/
```

**By Branch**

```
$ curl -H "Content-Type: application/json" --data '{"source_type": "Branch", "source_name": "$BRANCH_NAME"}' -X POST https://registry.hub.docker.com/u/$ORGANIZATION_OR_USER/$REPO/trigger/$TRIGGER_TOKEN/
```

**By Tag**

```
$ curl -H "Content-Type: application/json" --data '{"source_type": "Tag", "source_name": "$TAG_NAME"}' -X POST https://registry.hub.docker.com/u/$ORGANIZATION_OR_USER/$REPO/trigger/$TRIGGER_TOKEN/
```

**Note:** the `$XYZ` tokens are not meant to be environment variables but simple placeholders for the purpose of this comment.

This way, only a single image will be built. I hope that the wrong commands will be fixed soon. It took me some time to figure this out ...

**Comment by mfoll** [comment]
Right, thanks for your help. 
So the difference with what is written on the "build setting" page are:
- Replace `&#123;` with `{`
- Replace `&#125;` with `}`
- To build by docker tag, replace `docker_tag_name`with `docker_tag` 
I have to admit I was thinking the first two were on purpose... I tried again and indeed I confirm it works (only) with these three changes. Any error in the data will trigger all builds.

**Comment by nhsiehgit** [comment]
Sorry, indeed a bug. will update

**Comment by nhsiehgit** [comment]
Just deployed to production, this should be fixed now. closing
