### ISSUE TITLE
Official image sizes in Docker Hub are 3x off

### ISSUE THREAD

**Issue by ahmetb** [docker/hub-feedback#331]
> https://hub.docker.com/r/library/golang/tags/

| Tag | Size |
| --- | --- |
| 1.5 | 212 MB |
| 1.4 | 171 MB |

> **Reality**

![image](https://cloud.githubusercontent.com/assets/159209/9666517/6e3b18e8-522b-11e5-81cd-1a42c192a20f.png)

---

![image](https://cloud.githubusercontent.com/assets/159209/9666527/773521d2-522b-11e5-89ed-35d617933e2b.png)

**Comment by dnephin** [comment]
I've noticed this as well, it seems to be a problem for every repo

**Comment by thaJeztah** [comment]
Is it only accounting for the last layer, and not the intermediate images?

**Comment by dnephin** [comment]
@thaJeztah that was my initial guess as well, but it doesn't appear to be the case. https://hub.docker.com/r/dnephin/docker-custodian/tags/ shows 20Mb, but here's the `docker history` of that image:

```
IMAGE               CREATED             CREATED BY                                      SIZE                COMMENT
132b79a08643        2 weeks ago         /bin/sh -c pip install --no-deps -e /code       4.12 kB             
3a942de17a65        2 weeks ago         /bin/sh -c #(nop) ADD file:bb0907a9f765ce62c9   835 B               
6252075d10c5        2 weeks ago         /bin/sh -c #(nop) ADD dir:be799e78ee85de7a093   10.03 kB            
263966f97183        2 weeks ago         /bin/sh -c pip install -r /code/requirements.   8.829 MB            
b3f4ed5f3a19        2 weeks ago         /bin/sh -c #(nop) ADD file:03ac8700b861c11c40   180 B               
10524b691e9d        2 weeks ago         /bin/sh -c apk add -U python py-pip             44.1 MB             
bd2f93b328b4        2 weeks ago         /bin/sh -c #(nop) MAINTAINER Daniel Nephin <d   0 B                 
31f630c65071        3 months ago        /bin/sh -c #(nop) ADD file:98d5decf83ee59e1dd   5.254 MB   
```

I can't really see any correlation between the layers and the reported size.

**Comment by dnephin** [comment]
I think the issue is that the size is being calculated from the `content-length` header of the v2 registry, but that is not the same size as reported by the docker engine api. The layer in the registry is a `.tar.gz` so it's the compressed size.  I'm not sure what docker engine api size refers to.

**Comment by thaJeztah** [comment]
@dnephin ah, that would make sense, that it reports the compressed size. The "virtual size" reported by `docker images` is the combined size of all the images that make up the final image (so the tagged image, and all intermediate layers/images).

IMO, *ideally*, Docker Hub should report both, so that (as a user), I can see how much that will have to be *downloaded*, and how much disk space the image will take up once downloaded and uncompressed (although, docker will obviously needs space to store both)

**Comment by tomdee** [comment]
+1 - I see this as an issue too

**Comment by crisp-github** [comment]
Might be nice to see the build size in the Build Details

**Comment by tjanez** [comment]
I can confirm this also happens with other Docker Hub repositories.

For example, while `docker images` [reports size as 4.419 GB](https://travis-ci.org/genialis/docker-bio-linux8-resolwe/builds/110494466#L789), Docker Hub [reports size as 2 GB](https://hub.docker.com/r/resolwe/bio-linux8-resolwe/tags/).

Is there any enhancement for this in the pipeline?

**Comment by bcwalrus** [comment]
Looking into it. As mentioned above, it's the difference between compressed and uncompressed sizes.

**Comment by tjanez** [comment]
@bcwalrus, thanks! Please, keep us updated on the progress.

**Comment by ahmetb** [comment]
I'll reopen, I probably closed it out of no action being taken.

**Comment by J242** [comment]
Thanks! Fingers crossed for a solution!

**Comment by J242** [comment]
Actually I thought this message was in regards to this issue that I can't get no satisfaction on:
https://github.com/docker/for-win/issues/1736

**Comment by fgervais** [comment]
I can confirm that also. I took a python image thinking it would be 310.77 MB but it turned out to be 745 MB.

**Comment by adityasrini** [comment]
I expected an alpine-jre image from adoptopenjdk/openjdk12 to be 50MB...aaaaand it's 150 MB! It would be nice to visualize the final uncompressed image sizes through the CLI tool or other ways.

**Comment by thaJeztah** [comment]
I don't think it'll be possible for Docker Hub to display the uncompressed size (as it never receives the files uncompressed, so wouldn't know what the uncompressed size is). Perhaps the presentation could be improved to make clear that the sizes shown are the compressed size (thus the amount of data that will be sent over the wire)

/cc @meticulous-dft @renee-ners

**Comment by tstibbs** [comment]
It's a shame this issue hasn't really been looked at since it was opened over four years ago. The sizes as currently presented are very confusing and therefore more or less useless. I expect just about everyone that looks at them (that hasn't been burnt by this issue before) will assume that the number represents the resulting size of the image.

**Comment by thaJeztah** [comment]
@tstibbs it's definitely been looked at, but (also see my comment above), it's not a "simple" thing to solve. The registry shows the size of the assets you download, after which the (docker) daemon uncompresses the assets. The OCI distribution spec for registries (https://github.com/opencontainers/distribution-spec/blob/v1.0.0-rc0/spec.md) only defines a "Size" field in the Manifest for the media that's stored, which represents the size of the actual file; 

```json
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
   "config": {
      "mediaType": "application/vnd.docker.container.image.v1+json",
      "size": 1497,
      "digest": "sha256:19485c79a9bbdca205fce4f791efeaa2a103e23431434696cc54fdd939e9198d"
   },
   "layers": [
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 760770,
         "digest": "sha256:7c9d20b9b6cda1c58bc4f9d6c401386786f584437abbe87e58910f8a9a15386b"
      }
   ]
}
```

While it _would_ be possible to (based on the mediatype) determines that a file is a compressed file, and try to resolve the uncompressed size (`gzip -l` e.g.), this would require a separate index to be maintained (as it cannot be stored in the registry itself). In addition, the files themselves may be stored separate from where the registry itself is running (e.g.  stored on s3 or elsewhere).

**Comment by tstibbs** [comment]
@thaJetztah I understand that, what I was trying to say was that I think we should do more to deal with the confusion caused by the UI. Even if there's no way to show the 'real' size, I think it could be made clearer that the number shown is not the final size on disk. E.g. Something as simple as changing the heading to say "Compressed Size" and adding an explanatory tool tip would be a good first step.

**Comment by LaurentDumont** [comment]
Throwing my hat in the ring for this. I was looking at making my image smaller and was a bit puzzled that the Docker Hub upload reduced the size. :)

A warning or a "?" on the Hub would be nice.

**Comment by D-side** [comment]
As far as I can tell, now the UI of Docker Hub lists this number as "Compressed Size". Which should be enough to clear up the initial confusion.

Is this solved then? Or is showing uncompressed size also in scope of this issue?

---

💡 Bonus tip: you can get an idea of the size you're going to see on Docker Hub before you push the image by doing this:

```sh
docker save $IMAGE | gzip | wc --bytes
```

I haven't checked the precision of the result it produces, but I would expect it to be just a little bit different because it compresses the whole collection of layers instead of each layer individually. Depends on the contents, I suppose.

**Comment by tstibbs** [comment]
@D-side well it now says "Compressed Size" which is a good start, though if you mouse over the little i symbol it says "This size is calculated by summing the image's layers, of which are compressed" which has some missing words in it, so I'm not sure you'd call it 'solved' :p

**Comment by testman42** [comment]
> well it now says "Compressed Size" 

Where does it say that?
If I look at [ubuntu:focal](https://hub.docker.com/layers/ubuntu/library/ubuntu/focal/images/sha256-6f2fb2f9fb5582f8b587837afd6ea8f37d8d1d9e41168c90f410a6ef15fa8ce5) on DockerHub I see that it says just "SIZE", 27.27 MB below it, while uncompressed size is 73.9MB, and putting mouse over any part of that shows no tool tips or additional explanation.

Ah, I see. Before posting this I went look around and I see that yes, the [https://hub.docker.com/_/ubuntu?tab=tags](https://hub.docker.com/_/ubuntu?tab=tags) does say "compressed size" with the 🛈 next to it that shows the description.

I would argue that the site for the single image, example of which is the one I provided above, has so much empty space that it should be no problem to either show the uncompressed size next to compressed size or at least add "COMPRESSED" in front of "SIZE" and provide the tool tip with description.

**Comment by thaJeztah** [comment]
> I would argue that the site for the single image, example of which is the one I provided above, has so much empty space that it should be no problem to either show the uncompressed size next to compressed size or at least add "COMPRESSED" in front of "SIZE" and provide the tool tip with description.

Hmm.. do you mean; put size in front of each line? I think it would add a lot of "clutter" on the page, and just repeating the same information on every line, whereas now it shows what the column means (and a tooltip with mode details on what it means)

<img width="1062" alt="Screenshot 2020-09-10 at 15 49 12" src="https://user-images.githubusercontent.com/1804568/92739664-6a69c680-f37d-11ea-9f46-a50e2281f948.png">

**Comment by thaJeztah** [comment]
Oh, wait; I think I see what you looked at; you mean the layer details page? https://hub.docker.com/layers/ubuntu/library/ubuntu/focal/images/sha256-6f2fb2f9fb5582f8b587837afd6ea8f37d8d1d9e41168c90f410a6ef15fa8ce5

<img width="791" alt="Screenshot 2020-09-10 at 15 51 46" src="https://user-images.githubusercontent.com/1804568/92740026-b61c7000-f37d-11ea-8e3f-ec945ae63768.png">

Yes, I think that one should probably be updated as well, and show the same (`COMPRESSED SIZE` instead of just `SIZE`).

**Comment by testman42** [comment]
Yes, that is what I was referring to. Thank you for looking into it.

**Comment by thaJeztah** [comment]
I'm not on the Docker Hub team myself, but I'll try to find the right person and/or open an internal ticket 😅

**Comment by thaJeztah** [comment]
Looks like the layer details pages now show `COMPRESSED SIZE` (with a tooltip);

<img width="874" alt="Screenshot 2021-06-04 at 13 10 06" src="https://user-images.githubusercontent.com/1804568/120792772-4b781980-c536-11eb-983f-c04c8a5888d1.png">
<img width="787" alt="Screenshot 2021-06-04 at 13 10 15" src="https://user-images.githubusercontent.com/1804568/120792778-4d41dd00-c536-11eb-8457-fe17aa084976.png">

**Comment by testman42** [comment]
Which looks like the solution that we were looking for.
So this issue can be closed in my opinion.

**Comment by thaJeztah** [comment]
Yes, I think this should be ok to close 👍
