### ISSUE TITLE
Private repos limit

### ISSUE THREAD

**Issue by stepanic** [docker/hub-feedback#378]
I think that you have bug at Docker HUB, if private repos limit is used in web app, example 1/1 for free plan.
Anyone can create another free private repos with `docker push`.
How?
Example:
Existing repo name available in web dashboard `username/myrepo001` and 1/1 free plan is full.
Just push non existing repo with `docker push username/mynewrepo` and private repo will be created and with free account 2 private repos will be at `username` profile.

**Comment by forrest-lookback** [comment]
To add onto this since it still exists as a bug as of 2019/03/26 if you perform a push like this you can't pull the image down, and will receive the following error: `Error response from daemon: pull access denied for org/repo, repository does not exist or may require 'docker login'`

The only solution is to delete enough repos to get back below the limit, delete the repo which brought you over the limit, then recreate it.

**Comment by nebuk89** [comment]
Old issue and no longer exists. Closing
