### ISSUE TITLE
Teams not automatically added as collaborators

### ISSUE THREAD

**Issue by orlade** [docker/hub-feedback#421]
When I create a new private repository (automated build FWIW) with an organisation's account, I have to manually add the organisation's teams as collaborators on that repository. Often I forget and, frustrated, wonder why I can't pull my new private repository.

I would expect teams in organisations to work the same way as Bitbucket: if a user has read access within the organisation, then they are automatically granted read access to all of the organisation's current and future repositories. These permissions can then be adjusted on a per-repository basis.

For Docker Hub, I have a team with read access in the organisation. When I create a new repository owned by that organisation, I would expect that team to be automatically added as read-only collaborators on that new repository.

**Comment by ChristopherBiscardi** [comment]
Since access is determined per-repo (not on the organization as a whole), it wouldn't make sense to add teams that have read access to a single repo to every future repo.

However, it may be useful to consider what happens after a repo is created to make this interaction easier. For example, one potential option is changing the "landing page" after creating a repo to be the Collaborators page.

@jsouth Any thoughts on this?

**Comment by sds** [comment]
I'm a little surprised there hasn't been much movement on this, as this problem significantly impacts a team's ability to automatically create and push _new_ private images (i.e. images with names that were never pushed before) and immediately start using them. It's a huge hassle to remember to add the appropriate teams as collaborators, and not something that can currently be automated.

If there was an API available to add teams as collaborators to repositories, that would be one solution. However, it would be more preferable to be able to configure a team that is automatically able to collaborate on all "new" repositories so that administrators don't need to remember to configure collaborators with each new image.

Would be awesome to hear what @jsouth or others feel the appropriate workflow is here.

**Comment by deitch** [comment]
I am surprised this is sitting here a year later. We have a production ID for deployment. Each new repo should get this collaborator automatically, but it doesn't. That makes automated CI/CD rather painful with a human step.

**Comment by williamroberts** [comment]
+1

**Comment by chetanv-oi** [comment]
Please, Please, Please!

**Comment by Riz-cros** [comment]
+1

**Comment by Timer91** [comment]
+1

**Comment by Alyshtar** [comment]
+1

**Comment by Cameron-Carra** [comment]
+1

**Comment by Dalf91x** [comment]
+1

**Comment by xGhostFamous** [comment]
+1
