### ISSUE TITLE
webhook stuck in `pending` state

### ISSUE THREAD

**Issue by agilliland** [docker/hub-feedback#423]
Not sure why this would happen because the webhook went through fine, but my dockerhub repo is saying that the webhook call is still pending and it's not clearing.  This is also preventing new webhooks from firing.

<img width="867" alt="screen shot 2015-10-27 at 12 57 41 pm" src="https://cloud.githubusercontent.com/assets/1987787/10770786/60a411fe-7caa-11e5-819a-2b8a06be519f.png">

How can I ...
1. clear out the current pending state so that I can trigger new webhooks?
2. make sure that future webhook calls don't fall victim to this issue?

**Comment by themusk** [comment]
I wish to report you are not isolated with that problem. Me and my colleague experience the same misbehavior. Looking forward for the fix! :)

**Comment by ChristopherBiscardi** [comment]
@agilliland Webhooks are in a `pending` state because they expect a response request indicating success or failure. This is because each webhook is considered part of a Webhook Chain, which can be read about in more detail [here](https://docs.docker.com/docker-hub/builds/#webhook-chains).

This is a bug if it is preventing webhooks from sending on *separate pushes*, but it is the intended behavior if there is a second webhook in a single pipeline which is being blocked by the pending status.

@themusk @agilliland Can either of you confirm that the webhook that isn't firing is part of a different webhook chain (or a different push event)?

Additionally, Webhooks are undergoing some changes to make them easier to deal with.

**Comment by agilliland** [comment]
okay, so after letting this run for a while i can confirm the webhooks from separate pushes are firing just fine.  I had thought they weren't firing initially due to rather long wait times, but it looks like they are eventually being fired.

i'm not actually trying to chain my webhook calls, so maybe that's just a confusion more than anything.  i figured that if i only had a single webhook url defined that the system wouldn't care about the response and so seeing the `pending` state was surprising.

**Comment by ChristopherBiscardi** [comment]
@agilliland

>  i figured that if i only had a single webhook url defined that the system wouldn't care about the response and so seeing the pending state was surprising.

I agree. My current plan is to change the defaults when there is only a single webhook being created vs a chain of webhooks to make this interaction less surprising. That is intended to happen "soon" along with other changes.

> rather long wait times

We'll look into this.

**Comment by alexwebr** [comment]
Has the webhook chain behaviour changed? I can't seem to get the "chaining" to work as the documentation says:
https://docs.docker.com/docker-hub/webhooks/#chaining-webhooks
Maybe just a UI/UX problem on my part; it seems currently that webhooks all get issued at the same time and don't wait for each other.

**Comment by alexwebr** [comment]
I asked Docker Support whether chained webhooks are still supported; it appears they are not and that the documentation will be updated soon.

> Hi Alex,
> Thanks for contacting Docker Hub support.
> It seems that chained webhooks are no longer supported on Docker Hub.
> Let me notify our documentation team to reflect that.
> We apologize for the inconvenience.
> Thanks,
> [Name scrubbed]
> Support Engineer
