### ISSUE TITLE
I cant't change my Profile Photos

### ISSUE THREAD

**Issue by zjyExcelsior** [docker/hub-feedback#441]
It seems that there is not the choice for user to change profile photos with their own photos.

**Comment by kristiehoward** [comment]
You can set a profile photo by using a Gravatar account.

To link that account with your Docker Hub account so that your photo shows up, click on the dropdown for your username in the top right corner.

Click Username > Click Settings > Scroll down to Account Information > Enter your email for your Gravatar account in the Gravatar Email field > Click Save.

Hope that helps!

**Comment by zjyExcelsior** [comment]
It doesn't work.

**Comment by kristiehoward** [comment]
Do you have a Gravatar account with a profile photo set up? 

If you do not already, you can [create one](https://en.gravatar.com/support/how-to-sign-up/). Once you have that account setup, you can follow the instructions above to tell Docker Hub to use that account and the corresponding photo. Please make sure to use the email you signed up for Gravatar with in the 'Gravatar Email' field.

**Comment by zjyExcelsior** [comment]
Great! Thank you very much! Gravatar account is useful.

**Comment by ChristopherBiscardi** [comment]
Closing since this looks solved.

**Comment by ginppian** [comment]
thank you very much @kristiehoward =)

**Comment by guedim** [comment]
Thanks @kristiehoward.

**Comment by aggresss** [comment]
thanks a lot @kristiehoward

**Comment by anuudb** [comment]
Thank you @kristiehoward 👍
