### ISSUE TITLE
Button to start build is missing

### ISSUE THREAD

**Issue by DJBnjack** [docker/hub-feedback#443]
As title says, since a few days (after changes to the auto-build system), the button to start a build manually has been missing.

I know it is possible to set up a Build Trigger and POST to this endpoint - but for a simple change like settings the Docker Tag Name to 'latest' (which is not the case anymore by default), this button was perfect!

Any chance it's coming back soon?

OS: Windows 10
Browser: Chrome
URL: The "~/settings/automated-builds/" pages

![missing](https://cloud.githubusercontent.com/assets/315946/11015958/99c2b136-8572-11e5-988c-a657a9a7dee4.png)

**Comment by rrarunan** [comment]
@DJBnjack 
Manual build triggers are available for `exact match` rules like:
Name - `master` => Docker Tag Name - `latest`

If you did have one such rule here or in your earlier autobuilds you will see them.
Any suggestions on how you expect the `manual build` to work for `regular expression` rules?

**Comment by DJBnjack** [comment]
@rrarunan 
Thanks for the quick reply - I was however not referring to the Build Triggers.

A few days ago there was a green button on the page named something like "Build now". When clicking on it, the hub would start a new build. This would help for small changes at the hub not hosted in the repository, like the docker tag name.

**Comment by ChristopherBiscardi** [comment]
@DJBnjack @rrarunan was actually referring to the "Trigger a build" button, which will show up only for exact-match build rules since the introduction of regex-based build rules. The button can be found at the end of a build rule, as seen in the following screenshot:

<img width="1228" alt="screenshot 2015-11-13 00 01 24" src="https://cloud.githubusercontent.com/assets/551247/11141407/f1c146e2-8999-11e5-8992-ff5f34785896.png">

----

There is a related issue which is adding to the confusion. As of the creation of this ticket, there was no default `master -> latest` exact match rule by default (only a `.*` regex match rule for branches). This makes it look like there is no way to trigger a build manually.

The solution is to create a `master -> latest` build rule (as seen in the above screenshot). Because this rule is an exact match, the trigger button will show up for it.

**Comment by DJBnjack** [comment]
Ah - that clarifies and solves it for me!
Thanks a lot @ChristopherBiscardi and @rrarunan

**Comment by ChristopherBiscardi** [comment]
awesome :) 

Closing this.
