### ISSUE TITLE
Automated builds in state 'unknown'

### ISSUE THREAD

**Issue by DavidR91** [docker/hub-feedback#462]
Wondering whether there are any docs / details for why/how a build enters an 'unknown' state?

```
Build Code                  Build Status    Created         Last Updated
b6ryx63mpc3npe95nx5u8f9     unknown         an hour ago     43 minutes ago
```

Should I just consider this failed and trigger a new build, or is this indicative a problem with my project?

**Comment by DavidR91** [comment]
A subsequent attempt at a build has also failed. I also notice #459 related to unexplained build errors (~2 days ago) - is this issue actually an ongoing infrastructure problem?

**Comment by mghazizadeh** [comment]
@davidR91 this is an issue we are aware of.. the build is really in the Q to be scheduled, but due to a minor issue we are reporting the state as "unknown". there is no real need to retrigger it manually. we will fix this to have a clearer message in a few days. The build Qs over the last couple of days have grown abnormally large.  We are aware of it and actively working on this to move through the backlog applying as much compute power as we can. Apologies for the inconvenience but we're on it. please see http://status.docker.io  Please also take note of and leverage the new capabilities in the automated build system on docker hub to set dynamic (build) rules that only matter to you. http://blog.docker.com/2015/11/upgraded-autobuild-docker-hub/
