### ISSUE TITLE
Can't add another email address under settings

### ISSUE THREAD

**Issue by urbanchaosmnky** [docker/hub-feedback#502]
Unable to add another email address under Profile ->  Settings:
1. click settings
2. typed in an alternative email address in the New Email Field.
3. Received Error: Enter a valid email address.
4. Verified that the email address was correct. 
5. Reloaded Site and still experienced same issue.

**Comment by kristiehoward** [comment]
Hi @urbanchaosmnky, is that new email address associated with a Docker Hub account already? If so, it won't let you add that email.

If it's a gmail email (or one run by gmail), you should be able to add any text after a `+` to create an alias that you could use. i.e. you may not be able to add `hello@gmail.com` but you can add `hello+1@gmail.com` to the hub since it's not associated with an account. Will you please let me know if adding an alias or a different email does not work?

**Comment by nebuk89** [comment]
fixed. Closing issue :)
