### ISSUE TITLE
Repository links do not work/trigger

### ISSUE THREAD

**Issue by F21** [docker/hub-feedback#518]
I have tried the following:
1. Two different Github repositories as automated builds for 2 different docker hub repositories. 1 of the repos has the other one linked to it. Building the linked repo does not trigger builds of the other repo.
2. 1 Github repository feeding out into 4 automated docker hub build repositories. 3 of the repositories are linked to 1 of the repositories. Building the 1 linked repository does not trigger builds of the other 3.

**Comment by bcwalrus** [comment]
Repository links currently only works on non-regex build rules, because we don't want to blindly go out and rebuild all your Github branches. (Rather, we're coming up with a better way to do that. Would like to know what you think is the right behaviour here.)

So if you have repo B linked to an upstream repo A, and repo B only has regex build rules, then those are not going to trigger. If you'd like, give me the repo names and I can go take a look. Thanks!

**Comment by F21** [comment]
Ah, that makes sense!

Repos in question:
https://hub.docker.com/r/f21global/hdfs-datanode/
https://hub.docker.com/r/f21global/hdfs-journalnode/
https://hub.docker.com/r/f21global/hdfs-namenode/
https://hub.docker.com/r/f21global/hadoop-base/

Which are backed by this github repo:
https://github.com/F21/hadoop

I currently have the following build settings set up
```
tag /.*/ 
tag /.*/ latest
```

This allows me to achieve my use-case like so:
1. Only tags (releases should be built).
2. Build a tag when it is pushed to the git repo and set its tag name to be the same as the tag from the git repo.
3. Also, build the tag when it is pushed to the git repo and give it the tag name of latest.

The whole thing works pretty well at the moment except for:
1. Repository links don't work as mentioned.
2. It is wasteful that the images is rebuilt for the latest tag. There should be some way to just tag the latest successful build as "latest".

**Comment by nathan-osman** [comment]
I'm experiencing this problem as well. I've got [this repository](https://hub.docker.com/r/hectane/hectane/~/settings/automated-builds/) configured as follows:

![](http://i.stack.imgur.com/gSI3Q.png)

So if I understand correctly, whenever changes are pushed for the `ubuntu` repository, mine should be rebuilt as well. However, this isn't happening. Changes were pushed to `ubuntu` 3 days ago, yet my repository hasn't been rebuilt since December (two months ago).

What am I doing wrong?

**Comment by tbenst** [comment]
Hey @bcwalrus, I believe the following repo conforms to your requirements but still does not trigger builds. Am I missing something or is this functionality broken?

![screenshot from 2016-09-11 18-02-28](https://cloud.githubusercontent.com/assets/863327/18421994/f8bd988e-7849-11e6-9aaa-645f90c0d03a.png)

**Comment by tbenst** [comment]
Anyone from the docker team able to comment on if repository links work at all? @mghazizadeh @marcusmartins @akshayvyas

**Comment by arne-cl** [comment]
@bcwalrus Just like tbenst, I have repos without regex build rules [1-2] that are not updated
after the linked repository [3] got rebuilt.

[1] https://hub.docker.com/r/nlpbox/python-zpar/
[2] https://hub.docker.com/r/nlpbox/heilman-sagae-2015/
[3] https://hub.docker.com/r/nlpbox/nlpbox-base/

**Comment by brad-jones** [comment]
Well this is annoying, any update to this issue docker team????

**Comment by pkennedyr** [comment]
Thanks for the feedback. To clarify, when a repository link is added to an (automated) repository in Hub, it will automatically trigger a rebuild only if the linked repository is also included in the FROM line of your dockerfile. We'll make sure to update the UI to clarify this behavior.

**Comment by ayaz** [comment]
@pkennedyr Thanks. I ran into a similar issue where building of linked repo would not trigger a build of the other repo. I wasn't using regexes of any kind. The only mistake I had made was not have the FROM line match the name from the automated build. I am not sure if this is documented somewhere, I didn't find it.

**Comment by shoeper** [comment]
@pkennedyr it does not work.

I've linked https://hub.docker.com/r/shoeper/latex/~/dockerfile/ which uses FROM debian:testing to debian and debian:testing got updated two days ago but my automated build has not been updated, nor queued.

**Comment by shoeper** [comment]
Looks much like this **security issue** has not been taken care of for almost three years now.

Security issue because e.g. if debian gets a security update and the image is rebuild and people rely on repository linking their image won't be updated and thus will still have the vulnerable libraries. Having a look at docker hub such a scenario is very common.
