### ISSUE TITLE
Account: no way to delete an account

### ISSUE THREAD

**Issue by zosrothko** [docker/hub-feedback#532]
Hi

I did not found anyway to delete an account.

Can you provide such basic functionality?

thanks

**Comment by kizbitz** [comment]
Hi,
We do have this on our roadmap. In the meantime you can open a support ticket at https://support.docker.com with a request for deletion and we can delete an account for you.

Closing as duplicate: https://github.com/docker/hub-feedback/issues/11

**Comment by alexbaikal** [comment]
> 7 years passed and still no option!

yeah, only can deactivate an account which doesn't comply with GRDP

**Comment by oismaelash** [comment]
8 years passed and still no option!

**Comment by RaduTerec** [comment]
You can now request to delete your account by going to [their support page](https://hub.docker.com/support/contact) selecting Account -> Account deletion and filing a ticket for this.

**Comment by mac-chaffee** [comment]
Thanks for the tip @sereneowl !

Support directed me to submit a deletion request at https://preferences.docker.com/ so this might be the new process.

**Comment by ehvs** [comment]
This link tho should be more easily searchable, not hidden behind support request.

**Comment by NewteqDeveloper** [comment]
9 years passed, and still no option! (at least not visible on the site, the link @mac-chaffee provided seems to be privacy related). Does deactivating mean deleting (in the eyes of docker-hub)? Because those terms are different. But yet, deactivating states

![Image](https://github.com/user-attachments/assets/6f1af0e7-a9bf-4e82-878d-36ac5de7c27f)

`cannot be undone`... This is not deactivation, if it cannot be undone.

**Comment by Cherdenko** [comment]
docker ai told me i need to go to settings and click on the "Delete account" button. Only: there isn't one.

**Comment by gamedevCloudy** [comment]
if only the 10th year isn't about to start in like 6 weeks
