### ISSUE TITLE
Add button to trigger another build for a tag.

### ISSUE THREAD

**Issue by kizbitz** [docker/hub-feedback#620]
Currently the only way to get an automated build to re-trigger for a tag (in the event of an initial build error) is to remove the tag from Github, and then add it back.

**Comment by simonbrady** [comment]
While working around #522 I found that the Trigger button will show in the UI if you match an explicit tag name, but if you try to match a regex the button vanishes as soon as you type the trailing slash in the Name field.

This might be intentional (does triggering on a regex mean we should rebuild every tag that matches that regex, or just the latest?), but if so could it please be called out in the Automated Build docs?

**Comment by thasmo** [comment]
#708 is related.

**Comment by bcwalrus** [comment]
You can manually submit a build of any Git branch/tag using a build trigger. The source object will be evaluated according to the configured build rules, and kick off any matching ones: E.g.

    curl -H "Content-Type: application/json" --data '{"source_type": "Tag", "source_name": "v1.1"}' -X POST <trigger_url>

![triggers](https://cloud.githubusercontent.com/assets/171078/17529304/a0f53846-5e27-11e6-9dcb-c3300f503486.png)

**Comment by thasmo** [comment]
@bcwalrus, how would that work for the Docker Cloud?

**Comment by pkennedyr** [comment]
@thasmo Build triggers is on the Docker Cloud roadmap and will be released later this year.

**Comment by jojje** [comment]
I tried the curl examples for `jojje/gmail-relay`, but they did nothing.
There was no build triggered, nor a record in the _Last 10 Trigger Logs_ list, that anything had happened.

I tried both triggering on an existing tag, as well as `{"build": true}`, but none of them had an effect.

The only way to trigger a rebuild was to remove and re-add the tag in github.
I don't really like fiddling with tags in the git repo, since release tags are supposed to be immutable.

**Comment by farwayer** [comment]
@bcwalrus example works for me 👍

**Comment by martinyunify** [comment]
if the project is hosted on github, you can resend the trigger event on webhook configuration page on github.

**Comment by thasmo** [comment]
@pkennedyr What's the status on `Build triggers is on the Docker Cloud roadmap and will be released later this year.`?

**Comment by nandhini915** [comment]
The ability to trigger builds via the UI should be live. Go to your repository => build tab and retrigger the build. Here's a screenshot for further clarification.

![build trigger via ui](https://user-images.githubusercontent.com/2453622/42403501-819bbe50-8136-11e8-8f6c-9ad844541614.png)

**Comment by timwsuqld** [comment]
https://success.docker.com/article/trigger-a-build-for-an-automated-build-tag links to here, but this has been closed. @nandhini915 can we please get this reopened.
The trigger button you have shown only works for the latest tag, with the master branch. It doesn't work for existing git tags.

**Comment by ambsw-technology** [comment]
For @timwsuqld's requirement (and incidentally mine), see #708.  If the inbound link can be updated, that would be ideal.

**Comment by froblesmartin** [comment]
As said by @timwsuqld , this only works for the "latest" tag, and not the following ones :cry: is it going to be fixed?
