### ISSUE TITLE
Feature request: Triggering automated builds of multiple tags of an image

### ISSUE THREAD

**Issue by naamunds** [docker/hub-feedback#634]
I would like to trigger automated builds of multiple Docker tags of an image using a single HTTP POST request. I have not yet found a way to do that. Specifically, if I have a repo that has one Dockerfile for tags "preview" and "latest", and another Dockerfile for tag "futures", how would I programmatically trigger builds for both the "preview" and "latest" tags but not the "futures" tag?

Sending multiple HTTP POST requests back-to-back is not a good option because the requests could be throttled by DockerHub, in addition to performance concerns with sending multiple HTTP requests.

Based on the examples in the Build Triggers section in the Build Settings page of the repo, the four options are to trigger all tags, to trigger by Docker tag name, to trigger by source branch, or to trigger by source tag. All of my tags are in the same branch/tag in GitHub, so the last two options aren't applicable. I played around with different syntaxes for specifying multiple Docker tag names using the second option, such as {"docker_tag": "latest; preview"}, but I couldn't find anything that worked.

Is this supported? If not, I think it would be a valuable feature, as it would allow more flexibility in the triggering of automated builds.

**Comment by naamunds** [comment]
I asked this question a few weeks ago on the Docker forums but haven't gotten a response, so I decided to post it here also.  Here's [a link to the question there](https://forums.docker.com/t/how-to-trigger-automated-builds-of-multiple-tags-of-an-image/7587).

**Comment by bcwalrus** [comment]
@naamunds I think there are 2 parts to your question.

1. How to trigger builds for different tags (or build rules) for the same branch? You've actually found the solution, which is to specify `"docker_tag": "latest"` in the POST json. But that only support a single tag.

2. How to assign multiple tags to the resulting image of a single build? In this case, you'd like to build once, and push the image to multiple tags (which is relatively free). That is something we're working on. Right now, each build rule can only specify one tag. But there is a workaround: https://github.com/docker/hub-feedback/issues/384#issuecomment-197731025

**Comment by naamunds** [comment]
@bcwalrus Thanks for the suggestion. @MichaelSimons and I are looking into the workaround you mentioned to see if it works for us.

**Comment by flavius** [comment]
Any news on this? I have the same situation:

- multiple tags (anywhere between 5 and 1000), each with its own set of --build-args, in the same branch (I will call this "the build matrix)
- the build matrix is specified in a file in a specific directory
- there are multiple directories, each with its own build matrix, for different repositories
- not feasible to create a tag for each of them, it's just too many

Each of the entry in the build matrix is a slight variation of the previous one.

Reducing the number of tags is not an option. I have done that in the past by having "the image" being built at run-time, this is where I come from already, and I'm moving to prebuilt images because doing what I was doing was too slow when starting new containers (because it had to install the software that would otherwise be installed during build-time).

Regards,
Flavius Aspra
