### ISSUE TITLE
use the same image for “latest” and “vX.Y” auto-builds

### ISSUE THREAD

**Issue by meonkeys** [docker/hub-feedback#712]
Hi folks! Here at DockerCon. Alex suggested I post my feature request here.

I'm proposing an improvement on image auto-building for Docker Hub. I'd like Docker Hub to detect that a commit has a particular tag, and only build _one_ image for that git tag and for `latest`.

More details here: https://stackoverflow.com/questions/37650119/how-do-i-make-a-docker-hub-use-the-same-image-for-latest-and-vx-x/

Best,
-Adam

**Comment by pchico83** [comment]
Hi @meonkeys 
This is currently available using  a `post_push` hook: https://docs.docker.com/docker-cloud/builds/automated-testing/
You can define a build rule that matches ' /.*'/ with source type "Tag" and generates the tag "{source_ref}". In addition to this, your `post_push` would look like:
```
docker tag $IMAGE_NAME $DOCKER_REPO:latest
docker push $DOCKER_REPO:latest
```
We are working on documenting all these options better and improving our UI to make them easier to use, but I hope this helps in the meantime.

**Comment by meonkeys** [comment]
@pchico83 thanks, I'll give that a shot!

Do you want to answer the stackoverflow question too?

**Comment by meonkeys** [comment]
Verified.

In case anyone else is curious, [here's the change I had to make](https://github.com/meonkeys/docker-syncthing/commit/b9298d84ffbcee12100b3f053d4a8658d56a3647) so the most recent "vX.X"-tagged image is also tagged `latest`.

**Comment by mkuzmin** [comment]
So, every time you start a build, the `latest` is moved to this new image.

But what if I need to re-build old tags (because upstream dependencies were updated), or maintain multiple tags in parallel (like debian- and alpine-based images)?
It would be helpful, if we can move `latest` pointer between tags explicitly, like in official image [manifests](https://github.com/docker-library/official-images#instruction-format).
