### ISSUE TITLE
When deleting private repo, the private-repo-credit is not incremented

### ISSUE THREAD

**Issue by PepijnK** [docker/hub-feedback#714]
I accidentally named my private repo wrongly so I deleted it. Now I can't create a new one as my credit to create a private repo is zero.

**Comment by PepijnK** [comment]
I can't believe this is the default behaviour, since that would mean any mistake in naming or config will cost you one point of private-repo-credit, and those points are expensive! Please tell me it's a bug!

**Comment by pkennedyr** [comment]
Hi @PepijnK, Thanks for the feedback - what you're experiencing is NOT the expected behavior and appears to be a bug. If you're on a free plan, creating a single private repo and deleting the private repo should reset your available private repositories to 1 ("Using 0 of 1"). I just tested and am unable to repro - can you share your DockerID?

**Comment by PepijnK** [comment]
Maybe good to mention, I've created the private repo for an organization.
Op 9 jul. 2016 16:15 schreef "Ryan Kennedy" <notifications@github.com>:

**Comment by pkennedyr** [comment]
Thanks, @PepijnK. Only individual accounts are eligible for a free private repo, so that would explain the error you are seeing with an organization account.

**Comment by PepijnK** [comment]
Funny... and you think it's not a bug that I could create one?
