### ISSUE TITLE
404 page not found returns HTTP status code 200

### ISSUE THREAD

**Issue by friism** [docker/hub-feedback#741]
![image](https://cloud.githubusercontent.com/assets/126104/16966390/3c3e89d0-4db9-11e6-94e9-0d773462c5c9.png)

**Comment by narqo** [comment]
Does anyone aware, if the issue is scheduled to be resolved? 

This is very annoying because browsers tend to remember pages responded with 200 and suggest them when you type page's url. So every time I want to check with the documentation from, e.g. `wurstmeister/kafka`, Chrome suggests me `https://hub.docker.com/wurstmeister/kafka` instead of `/r/wurstmeister/kafka`, because I made this typo once.

**Comment by stefanbuck** [comment]
This issue also breaks [OctoLinker](https://github.com/OctoLinker/OctoLinker) a browser extension for Github which turns `FROM nodejs:latest` into a clickable link.
