### ISSUE TITLE
如何查看镜像依赖的系统版本

### ISSUE THREAD

**Issue by majinding** [docker/hub-feedback#765]
比如 在https://hub.docker.com/ 查询mysql
像 https://github.com/docker-library/mysql/blob/77f0a50ecd54edafe48ce3a2a328c22e9e7564a8/5.7/Dockerfile所编写的dockerfile
如何查看依赖的 FROM debian:jessie  这个镜像的系统版本。

近期从ubuntu14.04 迁移到16.04 就出现不兼容的问题。
麻烦有知道的大神帮忙指教下，谢谢。

**Comment by bcwalrus** [comment]
@majinding Your question is about inspecting the version of the `FROM` image. Right?

There are several ways to go about it:
- In your example, it says `debian:jessie`, so you know it's the Debian 8 "Jessie".
- Some Dockerfiles don't specify that. (Personally, I'd trust those images less.) But you could exec into the image and see for yourself.

In general, there is no good way to find out, and the `FROM` line is not 100% reliable. Because I can construct an Ubuntu 16.04 image from an Ubuntu 14.04 base image.

> 近期从ubuntu14.04 迁移到16.04 就出现不兼容的问题。

Ubuntu 16.04 is not compatible with 14.04. Yes, that's expected. You can't switch your base image from Ubuntu 14.04 to 16.04 and expect things to magically work. That is how Linux distributions work, and has nothing to do with Docker.

**Comment by majinding** [comment]
Thank you for your reply.
The reason I ask how to view the system version of the mirror, is that the system version of the problem caused by the start of the container, resulting in ubuntu16.04 can not work?
I have been very confused about the problem is that the ubuntu14.04 is built on the mirror can be normal operation, but then import into the 16.04 can not be normal operation, and this shows what the problem? Mirror or dependent system?
Also hope a lot of advice, thank you.

**Comment by bcwalrus** [comment]
> view the system version of the mirror

I don't understand what you mean by "mirror" or "system version". You can view the `Dockerfile` of `ubuntu:16.04` via the link on https://hub.docker.com/r/library/ubuntu/. Ubuntu doesn't use a version system within a release. Individual apt packages have their versions, and you can update them, or install a specific version.

If you see an error porting an application from 14.04 to 16.04, that is quite normal. This would probably happen even without Docker.

What's the error, btw?

**Comment by majinding** [comment]
thanks
