### ISSUE TITLE
Error: EXDEV: cross-device link not permitted, rename

### ISSUE THREAD

**Issue by lpgeiger** [docker/hub-feedback#852]
I'm getting this error in docker cloud, but not in quay.io . Quay builds perfectly. I don't know what a cross-device link is, in docker context.

The full error is:
Error: EXDEV: cross-device link not permitted, rename '/opt/meteor/dist/bundle' -> '/opt/meteor/dist/bundle-garbage-14tplr2'

**Comment by keyscores** [comment]
@pkennedyr @borjaburgos , any ideas why this may be? Seems to be intermittent.

**Comment by juicelink** [comment]
I've systematicly the same error since november, 12, building a node api

EXDEV: cross-device link not permitted, rename '/tmp/src/node_modules/babel-runtime' -> '/tmp/src/node_modules/.babel-runtime.DELETE'

all the js versions of my packages are fixed.

before november, 12 I had no problem to build my image
I build my app on the official image.
Last success build on node 6.9.1
 First failed build on v7.0.0
Today I've fixed the node version to 6.9.1 but builds continue to fail

**Comment by pchico83** [comment]
@juicelink do you mean October 12?

**Comment by juicelink** [comment]
Yes, sorry. Edited

**Comment by pchico83** [comment]
@juicelink can you provide the docker repo where this is happening? I have the feeling that this is a 1.12 regression, but we need to investigate further. Having a dockerfile that consistently incurs in this error will help to troubleshot and to find a fix.

**Comment by juicelink** [comment]
@pchico83 it's a private repo. I'll try to reproduce in a public one and come back to you

**Comment by pchico83** [comment]
@juicelink if I have the docker repo where this is happening, I should be able to reproduce it.

**Comment by juicelink** [comment]
@pchico83 here's a repo with the issue: juicelink/test-cross-device-link

I've rewritten my Dockerfile to avoid the issue.
I ran 2 npm install , one first in prod (for the serverside) and one in development (for building sources) with copying the module of the first npm install to avoid to redownload them
The issue was triggered at the 2nd npm install

I run now just 1 npm install (dev env) to build from the sources then npm prune (prod env) to get only my production modules

**Comment by pchico83** [comment]
@juicelink I am investigating it, but looks like an engine issue and probably the fix won't be available until docker 1.13 is released. Thanks for helping to troubleshot the issue.

**Comment by pchico83** [comment]
@juicelink looks like an issue with `npm` that they are fixing:
https://github.com/npm/npm/pull/13901

**Comment by caervs** [comment]
@juicelink there is also some good information at https://github.com/npm/npm/issues/9863

The tl;dr is npm combined with docker has problems when you try to move files in one layer to a path that exists in a previous layer (i.e. override one RUN command with another RUN command).

So a good tip is to try to do both installations in a single RUN command like

```
RUN npm i --production && cp -R . /tmp/src && ls /tmp/src && cd /tmp/src && npm i
```

I've tested with the example build you gave [here](https://github.com/juicelink/test-cross-device-link/blob/master/Dockerfile) and it worked.
