### ISSUE TITLE
Deprecate Images

### ISSUE THREAD

**Issue by minrk** [docker/hub-feedback#907]
I've deprecated a few images over the years, but I haven't seen a good way to communicate that to people, because they don't see any messages when they try to use the image. How can I best signal that a `foo/bar` image is deprecated, and a `other/better-bar` images should be used instead? I can update the description on the Hub, but nobody looks at those, as far as I can tell.

**Comment by schmunk42** [comment]
Ping @thaJeztah

**Comment by thaJeztah** [comment]
Docker Hub doesn't have such an option (not even sure if the registry spec would have something in the API to communicate such errors).

I think the best approach would be to;

- Clearly mark the image as deprecated in the README (obviously, that won't help for users not looking at Docker Hub)
- Perhaps push a new version of the deprecated image and make it print / log a warning?

I realise it can be a pain; some users just never update (frequently run into that myself with users reporting "bugs" with `<insert obsolete version of docker here>`)

**Comment by JeffUnderhill** [comment]
I realize this issue is somewhat old, but it is also still open and I just ran into a need for this myself. For example there's an official Docker image for Jenkins that has been deprecated in favor of the Jenkins community LTS image. The README clearly states this but it would also be useful if Docker Hub had a DEPRECATED tag (like the tags for "Container", "Linux", "ARM 64", "Base Images" etc...) as this would allow users to filter and identify deprecated images at a higher level and maybe even programmatically when pulling the image?

**Comment by silverwind** [comment]
I think npm does this pretty well. For docker, I could see a `docker deprecate <image>` (and `undeprecate`) command being made which after running would issue a warning every time that image is pulled.

My use case is deprecation of arch-specific images which have been moved to a multi-arch image.

**Comment by alexey-milovidov** [comment]
This issue is relevant for ClickHouse. We recently have moved from the old organization on DockerHub to another and want to migrate the users.

**Comment by uilianries** [comment]
I asked for it 2 years ago: https://forums.docker.com/t/mark-image-as-deprecated/104714

My point was using a label in the Docker recipe that identifies as deprecated. It could TRUE, or even a name for a new image to be used instead.
