### ISSUE TITLE
Webhooks - post to callback_url returning "Update not allowed"

### ISSUE THREAD

**Issue by maccyber** [docker/hub-feedback#943]
After the webhook is received I want to callback dockerhub with the status.
See "Callback JSON data" i [docs](http://docs.master.dockerproject.org/docker-hub/webhooks/)

When i post to the callback_url
with e.g. ```{ "state": "success" }``` as body I get response:

```json
{
    "statusCode": 400,
    "body": "Update not allowed"
}
```

Is this function removed?

Related 1: https://forums.docker.com/t/webhook-pipelines-dont-wait-for-callback/5813/2
Related 2: https://forums.docker.com/t/webhook-callback-failed-400-client-error-when-using-autodeploy/10011/6

**Comment by philipkueng** [comment]
Any news on this?

**Comment by christian-weiss** [comment]
Your link (http://docs.master.dockerproject.org/docker-hub/webhooks/) is no longer working. 
Looks like the Docker-Team forgot to disable the Cloudfront CDN at http://docs.master.dockerproject.org, as the origin has gone).
I think most recent documentation is here: https://docs.docker.com/docker-hub/webhooks/ 

On my last test to the docker hub callback URL with a request body similar to this:
```
{
  "state": "success",
  "description": "387 tests PASSED",
  "context": "Continuous integration by Acme CI",
  "target_url": "http://ci.acme.com/results/afd339c1c3d27"
}
```

i got:
HTTP CODE: `400 BAD REQUEST`
with headers:
```
Server: gunicorn/19.6.0
Date: Wed, 06 Nov 2019 17:33:49 GMT
Transfer-Encoding: chunked
X-Frame-Options: SAMEORIGIN
Content-Type: application/json
Strict-Transport-Security: max-age=31536000
```
and body:
`"Update not allowed"`

Some more questions, comments about this feature / documentation (https://docs.docker.com/docker-hub/webhooks/):

- Please describe "webhook status" vs "webhook callback status" more in detail. 
- Where are both statuses displayed? 
- Where is the target_url (which was transmitted in the payload to the callback URL) displayed in the Docker Hub WebUI? 
- What do you mean by webhook chain ? 
- What do you mean by "A chain request is only considered complete once the last callback has been validated." ? If i register multiple outbound webhook URL at docker hub, then all these URLs get called nearly at the same millisecond. List of registered outbound webhook URL: Should the second webhook be called only after a successful call to the first webhook URL? Or only after a callback of that webhook when returned status equals to success?

These questions are copied from my other issue (https://github.com/docker/hub-feedback/issues/1916) because they are more related to #943.

**Comment by christian-weiss** [comment]
Looks like this bug is existing since 16th apr. 2016 - 3,5 years now.
I have no hope that it will get fixed soon. As inbound- and outbound-webhooks are having bugs and bad documentation is the reason why docker hub is not often used in cross-vendor pipeline chain. I see no option to inject/link reports dynamically into docker hub WebUI atm.

**Comment by umariyoob** [comment]
@christian-weiss any update on this?

**Comment by ElusiveMind** [comment]
Looks like this is still an issue. Posting to the callback_url gives me the HTML of the DockeHub UI with a 200 code. Even with example JSON.
