### ISSUE TITLE
Headings text size is off in repo descriptions

### ISSUE THREAD

**Issue by antoineco** [docker/hub-feedback#949]
The headings text size is off in the repository descriptions:
* h1 and h3 are the same size
* h2 is much bigger than h1

Current rendering:
![issue-446](https://cloud.githubusercontent.com/assets/3299086/22612400/ba7527e2-ea70-11e6-8ff1-a155881ff09b.png)

I'm not a web designer but the following simulation looks way more acceptable:
![issue-446-2](https://cloud.githubusercontent.com/assets/3299086/22612557/b4e37792-ea71-11e6-9642-460df1a437f3.png)

`font-size` used for this simulation:
* h1: 2em
* h2: 1.75em
* h3: 1.5em
* h4: 1.4em
* h5: 1.25em

related #446

**Comment by hlfernandez** [comment]
This issue is still happening, it would be nice to have it fixed. Thank you for your help.

**Comment by lovato** [comment]
Yes, still happening. Looks awkward. If you look here:

- https://guides.github.com/features/mastering-markdown/

You get:

![image](https://user-images.githubusercontent.com/1213774/42818158-7ce34c34-89a6-11e8-8870-0b01cd8a8fe5.png)

But Dockerhub implementation makes it H2 > H3 > H1 > H4 > H5 > H6

**Comment by zyndagj** [comment]
Hello, could the Markdown description issues get elevated in priority?

Legible documentation is extremely important since Docker images are essentially black boxes without help text that often contain multiple programs. The archived Dockerfile is great when using automated builds, but users are left to rely on the (often missing) description when images are manually pushed to the Docker Hub.

Exposing documentation that users can easily parse and browse is impossible with the current markdown parser. Please either fix these issues or remove markdown formatting all together in favor of pre-formatted ASCII styling.

**Comment by lovato** [comment]
@manishtomar Sorry dragging you directly into this, but it's been 1.5y with no feedback at all, for a known issue, already fixed in 2016, which somehow got reintroduced back. Can you help assign this to someone at least for a feedback? I know that this is not critical at all, and I also know that everyone should be asking for help at the same time, but if someone can give a feedback, that would be awesome.

**Comment by manishtomar** [comment]
@lovato We've changes in UI coming in a 1-2 months during which this issue will be fixed.
