### ISSUE TITLE
Protected tags for persistent & immutable Docker Hub images

### ISSUE THREAD

**Issue by dhimmel** [docker/hub-feedback#958]
I'm looking for a way to prevent a Docker image at a specific tag from being overwritten or deleted. For example, other images should be able to extend my image at a specific tag without worrying that the image will change or disappear. Furthermore, we're using Docker images [for scientific reproducibility](https://doi.org/10.1101/056473), which will benefit from persistent & immutable archiving of images.

Currently, it's really easy to overwrite an existing image even when you're using tags for versioning. One accidental `docker push` can rewrite existing tags. Similar to how GitHub has protected branches, it would be great to have protected tags. This would prevent user error from overwriting an existing Docker hub image (excluding `latest` perhaps).

Is there already a way to accomplish this? If not are there any plans to help with image persistence and immutability?

**Comment by tedmiston** [comment]
I'd really like to have this feature in Docker Hub as well.  It looks like it's [already supported in Docker Trusted Registry](https://docs.docker.com/datacenter/dtr/2.4/guides/user/manage-images/prevent-tags-from-being-overwritten/) in Docker EE.

I wonder if it's something that will make it back into Docker Hub for normal users?

**Comment by KJlmfe** [comment]
Really need +1

**Comment by astleychen** [comment]
+1

**Comment by shyam-biradar** [comment]
+1

**Comment by feeblefakie** [comment]
+1

**Comment by lucasbasquerotto** [comment]
Immutable tags in Docker Hub would be great, and I also think that Official Docker hub images shouldn't have tags updated (if needed, create a new tag, like `somerepo:sometag-01` or `somerepo:sometag-20190808`). Even if the tag name becomes big, this is much better than have tagged images (that aren't `latest`) changed.. 

I had a surprise today when `composer:1.8.6` was **incompatible** with php `7.3.7` (the image had `7.3.8` installed). **It worked fine before**, and when looking at the repository, I saw that the tag was updated 6 days ago (so it was probably `7.3.7` before). 

For now I just created an image with the only instruction being `FROM composer:1.8.6` and pushed it, so that I make sure not to change it, and use this image to install the Wordpress packages.

This is just an example, but it seems that even for official images the **tags are being used more like branches** (maybe because there isn't a separate concept regarding branches and tags for docker images?). 

I saw [this documentation](https://docs.docker.com/ee/dtr/user/manage-images/prevent-tags-from-being-overwritten/) about setting on immutability, but it seems it's for Docker Enterprise (like @tedmiston said before).

**Comment by tlvu** [comment]
+1

**Comment by tlvu** [comment]
Totally agreed with all comments here.  Having existing image tag overrideable is a huge security risk.

Someone can setup an auto-build repo, perform the auto build to claim the image is from an inoffensive code, then override the image built by auto build with malicious image.

User is fooled into thinking the malicious image is from the auto build with was originally from the inoffensive code.

**Comment by dbyrns** [comment]
+1

**Comment by philmadden83** [comment]
+1

**Comment by thaJeztah** [comment]
To get more visibility, perhaps this issue would be more suitable for the public roadmap;   https://github.com/docker/roadmap/issues. Would someone be interested in writing up a summary and create a ticket there?

**Comment by academ1c** [comment]
+1

**Comment by thaJeztah** [comment]
I see there's a roadmap issue here; https://github.com/docker/roadmap/issues/85

Let me lock this issue in favour of that one; feel free to upvote and/or comment on that issue
